### ISSUE TITLE
Upgrade to AOSP DeskClock - Material You

### ISSUE THREAD

**Issue by BluePixel4k** [BlackyHawky/Clock#10]
Upgrading the app to the new design from the LineageOS Clock 12 or the new AOSP DeskClock app would be awesome!

Screenshots:
<img src="https://user-images.githubusercontent.com/77979781/178105594-f8f8fed4-e225-4619-b14f-60af7d1ebd46.png" width="250" /> <img src="https://user-images.githubusercontent.com/77979781/178105600-1ed75e0e-53c0-4639-887e-2de9aaa5621f.png" width="250" />

**Comment by BluePixel4k** [comment]
I just saw that you have already updated the new-clock app (without fdroid) to the new AOSP deskclock app. 
https://github.com/qw123wh/new-clock/releases
Will the f-droid version follow next?

**Comment by qw123wh** [comment]
Yes, you can start trying the updated app, but I think it conflicts with the old one and so you have to uninstall the old one and install the new one. There are other small things that I would like to improve, then when it is finally ready, it will be released on Fdroid.

**Comment by BluePixel4k** [comment]
Yes, I had to reinstall it. But it runs fine, thanks!
I just noticed that the slider to turn on/off alarms is slightly jerky when pressing.

> There are other small things that I would like to improve, then when it is finally ready, it will be released on Fdroid.

That makes sense. 👍🏼
