### ISSUE TITLE
Azores cities for world clock

### ISSUE THREAD

**Issue by cy8aer** [BlackyHawky/Clock#101]
**Is your feature request related to a problem? Please describe.**

There are no places from the azores selectable in the world clock (though there exists a homezone azores). It is -1 hour from London/Lissabon time (with summertime).

And for addition: They have three capital cities: Horta, Ponta Delgada, Angra do Heroísmo - see https://en.wikipedia.org/wiki/Azores

**Describe the solution you'd like**

A place e.g. Ponta Delgada selectable (main city) to select azores time

**Use case**

Simply have a place from the azores selectable.

**Describe alternatives you've considered**

... or azores (as a global place for world times)

**Comment by BlackyHawky** [comment]
@cy8aer 
The Azores is already included in the list of time zones. Isn't that enough? 🤔

**Comment by cy8aer** [comment]
Not if you want the Azores in your world clock list. There only cities are selectable.

* Go to tab "Clock"
* Tap Earth icon
* Search a city (e.g. Ponta Delgada)

Expected:

City is found and can be used as world clock in you list

Actual:

No selectable city from the Azores time zone

Or I did not understand the concept there and there is another way to get a world clock there for this time zone.

**Comment by cy8aer** [comment]
Crazy enough that a few islands have their own timezone ;-)

**Comment by cy8aer** [comment]
And for addition: They have three capital cities: Horta, Ponta Delgada, Angra do Heroísmo
