### ISSUE TITLE
M3 navigation bar active indicator 

### ISSUE THREAD

**Issue by BluePixel4k** [BlackyHawky/Clock#102]
**Describe the solution you'd like**
 Please add the active indicator from M3 to the navigation bar, like this:
![Screenshot_20240926-090705_1_1](https://github.com/user-attachments/assets/867405a4-245d-48f1-af0f-a5eee6844df6)

https://m3.material.io/components/navigation-bar/overview

**Use case**
Following the M3 guideline. 
It's easier to see which menu is selected.

---

Thank you! :)

**Comment by BlackyHawky** [comment]
I'm not sure I agree with this improvement, as it was deliberate to remove this pill for two reasons:
- To clean up the interface;
- To make the icon animations more prominent.

Moreover, other applications such as GitHub's do not display this type of indicator. We can't say that our application isn't modern, for example.

Finally, the icons and the texts of selected tabs are highlighted with an accent color, and the name at top left clearly indicates which tab we're in.

With all these reasons, I'm not sure that adding yet another indicator is necessary.

**Comment by BluePixel4k** [comment]
Maybe this pill could be optionally enabled via a setting?
Because for me, when I switch into this app, it's look's like something is missing in comparison to other material you apps.

I haven't installed the official Github app, but in the screenshots it doesn't look like the app follows the M3 guidelines.
So it's not a fair comparison.

**Comment by BlackyHawky** [comment]
When I use the GitHub application as an example, it's only because it has an bottom navigation menu.

In any case, don't worry, I'll take your request into account. 

A setting can be added to the "Interface" settings.

**Comment by BluePixel4k** [comment]
> A setting can be added to the "Interface" settings.

That  would be awesome, thank you!

**Comment by BlackyHawky** [comment]
@BluePixel4k 
Can you test the attached apk and give me your opinion please?

[Clock_2.8_beta-debug.zip](https://github.com/user-attachments/files/17173650/Clock_2.8_beta-debug.zip)

**Comment by BluePixel4k** [comment]
@BlackyHawky Thanks a lot, looking good!

Maybe you could adjust the colors of the fonts and icons a bit in this mode. 
The Google Clock (left) and your Clock app (right) for comparison:

<img width=200 src="https://github.com/user-attachments/assets/22a504f3-f04b-45fe-bf64-bb1d951e2429">
<img width=200 src="https://github.com/user-attachments/assets/f58e5de9-26dc-4f2d-9723-1e9687bb1ce6">

I mean, coloring the selected icon and font less and the unselected ones a bit more.
But this is just fine tuning and not mandatory :)

**Comment by BlackyHawky** [comment]
> Maybe you could adjust the colors of the fonts and icons a bit in this mode.

It seems to come from your device accent color.
Here's what it looks like on mine (Android 12):

| Day mode | Night mode |
| :------: | :----: |
| <img width=200 src="https://github.com/user-attachments/assets/9cf622db-b029-4efc-bfc6-1b7b22718fb6"> | <img width=200 src="https://github.com/user-attachments/assets/06790a67-68e8-4db9-bf1c-7e327e4aa312"> |

You can see that the color contrast is good.

I have to test with my tablet with Android 14 ; not sure I'll change the other colors.

**Comment by BlackyHawky** [comment]
After a few tests on my tablet using different accent colors, the contrast is good so I won't be changing the colors of the icons or anything else.

**Comment by BluePixel4k** [comment]
Yes, overall the contrast is good, but I would prefer that the unselected menus get a quiet Monet color (currently they look static) and the selected one get a less intensive color than they have now.
Do you know what I mean?

**Comment by BlackyHawky** [comment]
> Do you know what I mean?

No I don't.

In any case, when I see your screenshots, the color difference is too small for me to waste time working on it.
And I'm not sure that when we switch between 2 different applications, we'll be surprised by the current colors.
Finally, as you said above: "_But this is just fine tuning and not mandatory :)_"
