### ISSUE TITLE
Add setting to disable fade transition

### ISSUE THREAD

**Issue by privacyfreak84** [BlackyHawky/Clock#105]
**Is your feature request related to a problem? Please describe.**
Perhaps, if being dissatisfied by the addition of the fade transition in the settings pages counts

**Describe the solution you'd like**

Revert the addition of the fade animation in the settings pages

**Use case**

The latest animation makes the experience of using the app less snappy and, in fact, somewhat slow even. There is too long a delay between clicking on anything in the settings page  (and also the settings icon) and having the necessary information be displayed on the screen. The old animation, in my personal opinion, was perfect and did not need changing.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by BlackyHawky** [comment]
@privacyfreak84 
No need to worry about this.
In the next version I plan to add a setting to enable this animation and this setting will be disabled by default 😉

**Comment by privacyfreak84** [comment]
Thanks 🙏
