### ISSUE TITLE
Timers that persist after a reboot

### ISSUE THREAD

**Issue by yephny** [BlackyHawky/Clock#107]
**Is your feature request related to a problem? Please describe.**
I had a timer running for something important while I was testing something entirely unrelated on my device, which caused an unintended reboot and I lost my timer (the timer resets)

**Describe the solution you'd like**
The app could get the time data when a timer is started and save this data permanently (until the timer is done). This would allow the app to compare the current time and the time data saved to resume the timer.

**Use case**
It's a measure.

**Comment by BlackyHawky** [comment]
@yephny 
Impossible to reproduce on my 2 devices: Huawei with Android 12 and Samsung tablet with android 14.

Can you please provide :
- the version of the application used;
- the brand of your device;
- android version;
- ROM of your device;

> which caused an unintended reboot and I lost my timer (the timer resets)

What happened to make your device reboot unexpectedly? Maybe that's what caused the timer to go off, in which case it's not related to this application.

**Comment by yephny** [comment]
@BlackyHawky I manually rebooted my device and just as you said I couldn't reproduce it. It had to have something to do with what caused the unintended reboot.
