### ISSUE TITLE
ability to hide or rearrange bedtime tab

### ISSUE THREAD

**Issue by iJahangard** [BlackyHawky/Clock#108]
Bedtime tab is contain only one card and can be easily implemented in alarms tab
In other hand some users lile me don't use it at all so it might be better to have an ability to completely hide it

**Comment by BlackyHawky** [comment]
I agree that the sleep mode is useless, but some users want to keep it.
Especially since I don't intend to work on this mode.

I'm closing this topic because it will be taken into account in #28.
