### ISSUE TITLE
Automatically delete alarm after it has rung

### ISSUE THREAD

**Issue by tockudex** [BlackyHawky/Clock#110]
**Is your feature request related to a problem? Please describe.**
This issue is only a feature request.

**Describe the solution you'd like**
Add an option per alarm which automatically deletes the alarm after it has rung once.

**Use case**
This option could help you avoid having a “graveyard” of alarms.

**Comment by BlackyHawky** [comment]
This enhancement could indeed be added.

**Comment by don-dolarson** [comment]
> Add an option per alarm which automatically deletes the alarm after it has rung once.

This is exactly how the v2.7 works for me and all I can tell is I do don't like the auto deletion of run and dismissed alarms. Do it possible to choose not force anyone's preferences.

**Comment by don-dolarson** [comment]
I just tested the behaviours and alarms aren't auto deleted after they were run once and an action to dismiss has been taken. They're auto deleted if you dismiss them from the notification panel before any of them run.

**Comment by tockudex** [comment]
> Do it possible to choose not force anyone's preferences.

Of course, it should not be forced on anyone, same as for the option to turn off the alarm after the ringtone ended.

**Comment by BlackyHawky** [comment]
> They're auto deleted if you dismiss them from the notification panel before any of them run.

If you remove them from the notification panel, they are not deleted, but only disabled or reported. The alarm still appears in the alarm list.

What I was thinking of doing (if I'm able) is creating a button on the extended alarm view which, when activated, will remove the alarm from the alarm list only if it is stopped and not reported.


This button will be disabled by default and will only be visible if no day of the week is selected.

**Comment by don-dolarson** [comment]
> > They're auto deleted if you dismiss them from the notification panel before any of them run.
> 
> If you remove them from the notification panel, they are not deleted, but only disabled or reported. The alarm still appears in the alarm list.
> 
> What I was thinking of doing (if I'm able) is creating a button on the extended alarm view which, when activated, will remove the alarm from the alarm list only if it is stopped and not reported.
> 
> This button will be disabled by default and will only be visible if no day of the week is selected.

Whaaat? It's not how it works for me.
Dismissed alarms are completely deleted and I need to restore my backup every day to get all alarms with their different settings back. Just recently started using this clock v2.7 and it's how it worked. Updated to v2.8 yesterday and it still works the same way. LineageOS 20 rooted with Magisk.

**Comment by BlackyHawky** [comment]
@qw123wh, @odmfl, @Nilsu11 
Do you have the same behavior on your devices, i.e. when you dismiss an upcoming alarm before it is triggered from the notification panel, it is removed from the alarm list?

Impossible to reproduce on my devices since I've been working on this project.

**Comment by don-dolarson** [comment]
I've recorded the screen this morning.

https://drive.proton.me/urls/4CQFF9SVS4#XPUIfkn2pe_t

First two alarms not showing in the alarm list, 5:03 and 5:05 were automatically dismissed because they ended and this is how I set them up. 5:07 rings and is dismissed manually then all upcoming alarms from 5:09 on has been dismissed manually too and every of them is gone.

**Comment by BlackyHawky** [comment]
@don-dolarson 
I'm sorry but it's impossible to reproduce what you describe on my two devices. 😬

- Can you please provide the log file from the moment you created the alarms?
- What model is your device?
- I assume you didn't install the application as a system app?
- Is it the same with the LineageOS app? (apk attached below)

[DeskClock-LineageOS-release.zip](https://github.com/user-attachments/files/17354928/DeskClock-LineageOS-release.zip)

**Comment by qw123wh** [comment]
@don-dolarson Hi, from your screen recorder it seems that you are using a Custom Rom, (I also have some devices with custom rom) the problem on my devices does not appear. I think it is a ROM bug. I simply suggest you either change ROM or report the bug to the maintainers of that ROM

**Comment by don-dolarson** [comment]
It doesn't happen on the stock LineageOS clock. I've just reset the application and set all alarms from scratch. Let's see tomorrow ✌🏻

**Comment by qw123wh** [comment]
> It doesn't happen on the stock LineageOS clock. I've just reset the application and set all alarms from scratch. Let's see tomorrow ✌🏻

Also try uninstalling and reinstalling the app

**Comment by don-dolarson** [comment]
Cleaning the cache and data which I did before should be enough.

**Comment by don-dolarson** [comment]
It looks like alarms aren't deleted when dismissed anymore. Maybe it is some setting which doesn't cooperate. Let's find out 😀

**Comment by BlackyHawky** [comment]
@qw123wh @odmfl @Nilsu11 @tockudex @don-dolarson 

I've been working on it and it will be available tonight or tomorrow.
It seems that the function already existed but wasn't used, so it wasn't difficult to implement.

I'd like to know: should the button be enabled by default?

Remember: this button will only appear and work if no day of the week is selected.

Edit: In my opinion, it should be activated by default, as it's a punctual alarm that won't be repeated on another day.

**Comment by tockudex** [comment]
Great news !

I don't think that the button should be enabled by default, as it could confuse/surprise some users.
Your reasoning makes sense too. Ideally, there would be a toggle to make it the default behavior/deactivate in the app settings.

**Comment by BlackyHawky** [comment]
I'd like to avoid adding an extra setting.
The list of alarm settings is already quite long...

When I talk to a friend who doesn't know the application, he tells me that it should be enabled by default, because it's the principle of an alarm that will only be used once.

🤔

**Comment by qw123wh** [comment]
I think users including me are used to the current solution, better a button or flag to enable/disable the function or in the settings.

**Comment by odmfl** [comment]
I also think that the user should be given the option to choose. In my specific case, I don't use alarms programmed for multiple days, I have many alarms at different times because I work shifts in different time slots, so each day the alarm is based on the work shift. By automatically deleting the alarm after it has rung, I am forced to set a new alarm every day, while currently I have all the alarms saved and activate them when needed. So for me it would be preferable to have an option to be able to activate/deactivate this function.

**Comment by BlackyHawky** [comment]
Thank you for answering my question.
So I'll add a new setting in the alarm settings.
This button will only appear if this setting is enabled.

FYI: I realized while reading the code that by default, alarms that don't have days of the week checked should be deleted as soon as the ringing is over, as indicated in this [piece of code](https://github.com/BlackyHawky/Clock/blob/0214eeb0593f118f625ab11ae117360b187dd100/app/src/main/java/com/best/deskclock/alarms/AlarmStateManager.java#L205-L208).
When this topic will be closed, we'll make better use of this existing function, which I've never modified in my memory.
