### ISSUE TITLE
Start alarm vibrating only before increasing volume

### ISSUE THREAD

**Issue by bartlibert** [BlackyHawky/Clock#111]
**Is your feature request related to a problem? Please describe.**
The lowest volume for the alarm on my phone is still quite loud and wakes up my partner and/or children.

**Describe the solution you'd like**
It would be ideal if there is a possibility to have "gradually increase volume" start at "no volume", with just vibration.

**Use case**
Example scenario:
- I configure the alarm volume to be gradually increasing
- I configure the alarm volume to increase every 30 seconds
- I configure the alarm to vibrate
- When the alarm is triggered, the phone just vibrates for 30 seconds, after that, the alarm sound is played at the lowest volume and the volume increases every 30 seconds

**Describe alternatives you've considered**
Use another app, but I don't want to, I like this one too much

**Comment by BlackyHawky** [comment]
> The lowest volume for the alarm on my phone is still quite loud and wakes up my partner and/or children.

Strange that the volume is still loud, as on mine it's almost unnoticeable. So it's certainly related to your device model.

I'm afraid this request is really too specific to be implemented in the application.

I'm also afraid that if this request is accepted, other users will ask for other specific scenarios, and that could make a mess of the settings.

For the moment, I don't plan to work on that.

An alternative to consider is to set the volume to the lowest setting, set the gradual volume to 60 seconds and activate the vibrator.

**Comment by bartlibert** [comment]
It must be phone specific (motorola) indeed, because I did not have the issue on my previous phone.
I'll try to get around it with a custom sound file maybe, I'll see.
Thanks for the quick answer (and great app)
