### ISSUE TITLE
when time is 0:22 and 12hour-format.it prints "am 12:22"

### ISSUE THREAD

**Issue by yjdyamv** [BlackyHawky/Clock#112]
**Describe the bug**

when time is 0:22 and 12hour-format.it prints "am 12:22".it is strange and uncomfortable.

**To Reproduce**

**Expected behavior**

**Screenshots**

**App version**
v2.8

**Device (please complete the following information):**
 - Model: Huawei MAG-AL40
 - OS: HarmonyOS 3.0

**Additional context**

**Comment by BlackyHawky** [comment]
Can you specify the language of your device?

**Comment by BlackyHawky** [comment]
Can you please provide a screenshot?

**Comment by yjdyamv** [comment]
<img width=200 src="https://github.com/user-attachments/assets/9e6ec09e-81ff-4a73-a157-8e3fbd6705df">

**Comment by BlackyHawky** [comment]
@yjdyamv 
What language is your phone in?
Maybe there's a problem in one of the strings, but I'm not sure.
Strange that the writing is from right to left...

Is it the same with the digital widget (the horizontal one)?
Is it the same in the alarm list display?

**Comment by BlackyHawky** [comment]
@yjdyamv 
Can you please answer my questions?
I'd like to try and find out what's wrong.

**Comment by yjdyamv** [comment]
My language is simplified Chinese.The alarm is normal.digital widget is normal. I apologize for my late response. I recently don't log in github.

**Comment by yjdyamv** [comment]
My language is simplified Chinese.The alarm is normal.digital widget is normal. I apologize for my late response. I recently don't log in github.

**Comment by yjdyamv** [comment]
Model: Huawei MAG-AL40  
OS: HarmonyOS 3.0

**Comment by yjdyamv** [comment]
App version :2.8

**Comment by BlackyHawky** [comment]
@yjdyamv 
> I apologize for my late response. I recently don't log in github.

No worries.

Is it the same with the screensaver? I forgot to ask you.

**Comment by yjdyamv** [comment]
<img width=200 src="https://github.com/user-attachments/assets/b0fa412c-ae3d-446a-a4f3-eddacadcb3a4">

Yes,this problem is still extential, but l think it only occurs when time is 0:00-1:00,  because I just adjusted my time zone, and now the time is displayed correctly at 1:07.

<img width=200 src="https://github.com/user-attachments/assets/c71bbb3a-492e-4735-9c8a-146abe8a8c51">

This is the experiment screenshot.

**Comment by BlackyHawky** [comment]
After some research, this time is a conventional display applied in programming.

Source [here](https://en.m.wikipedia.org/wiki/12-hour_clock). 

I wouldn't change that, especially as it's the same display on other applications.

**Comment by yjdyamv** [comment]
Thank you for telling the tradition, when i meet that, i just treat it as a bug. 😅 .i see it.
