### ISSUE TITLE
Add "Shake" or "Flip" settings to stop timers like alarms

### ISSUE THREAD

**Issue by bluesdataventure** [BlackyHawky/Clock#115]
**Is your feature request related to a problem? Please describe.**

Shake to dismiss or Flip to dismiss does not exist for timers.

**Describe the solution you'd like**

Add shake to dismiss or flip to dismiss for timers.

**Use case**

I use the timers for exercise and when I'm in awkward positions it hard to click the tiny dismiss button. It would be SO HELPFUL if I could just flip or shake to dismiss my timer.  

**Describe alternatives you've considered**

So I poked around F-droid and did not easily find any timers that had shake to dismiss or flip to dismiss a timer. But I did not look that hard. I like this application better than the others I've found and this is already implemented for the alarms. So I was hoping it wouldnt be that difficult to implement for the timers. 

**Additional context**

I don't know if this would be possible, but what about a double tap to dismiss? That would be pretty cool!

**Comment by BlackyHawky** [comment]
@bluesdataventure 
I'm not against adding this improvement. I'll take a look if it's difficult or not to implement.

Currently, you can use the volume buttons to stop the timer (only works if the expired timer appears on the lock screen).

In the next version (which I'll publish soon) you'll be able to set a duration that will automatically stop the timer (5, 10, 20, 30, 60 seconds or at the end of the ringtone).

**Comment by bluesdataventure** [comment]
@BlackyHawky thank you for considering my improvement. 

I looked at a bunch of clocks and I really liked yours the best. 

Great job with the app.

**Comment by BlackyHawky** [comment]
This enhancement will be available for the next release. 😉
