### ISSUE TITLE
Next alarm widget shows incorrect time for next alarm

### ISSUE THREAD

**Issue by D3cahexatrisCode** [BlackyHawky/Clock#116]
I created widget Next alarm (Следующий будильник) 2x1 I set alarm on 06:10 next day morning, widget shows next alarm will be 23:00 today, but there is no alarm for 23:00 today
See screenshots

<img width=200 src="https://github.com/user-attachments/assets/755527d3-1eab-42bf-8ae1-7fb15bec82fe">
<img width=200 src="https://github.com/user-attachments/assets/a0ba8fc9-f3f1-424a-b8e8-58a5632dc045">

**Comment by BlackyHawky** [comment]
This topic is identical to #61.
It's all explained [here](https://github.com/BlackyHawky/Clock/issues/61#issuecomment-2169219832).

Please respect the template next time.
