### ISSUE TITLE
Recurring Alarms: Holiday Suggestions and Flexible Disabling

### ISSUE THREAD

**Issue by y-r-v** [BlackyHawky/Clock#118]
Thank you for developing such a wonderful app! I have a suggestion that may help improve it a bit.

**Is your feature request related to a problem? Please describe.**
Currently, when a recurring alarm is set (e.g., Monday to Friday), users have to manually disable the alarm for specific days or holidays (e.g., Christmas). This can be inconvenient and may lead to missed alarms.

**Describe the solution you'd like**
When a user chooses to disable a recurring alarm, the app could prompt them to confirm whether they want to disable all instances of the alarm or just the next occurrence. This feature would provide users with greater flexibility and control over their alarm settings.

There are several reasons why a person might want to disable a recurring alarm:

- **Holidays or Special Events**: Users may want to turn off their alarms for specific holidays or special occasions when they do not need to wake up at their usual time. In this particular case, the app could somehow anticipate holidays and suggest to disable alarms.
- **Sick Days or Personal Time Off**: If a user is unwell or taking a day off, they might prefer to disable the alarm for just that day rather than for the entire week.
- **Schedule Changes**: Sometimes, users may have a temporary change in their schedule (e.g., a meeting or event) that requires them to sleep in or wake up at a different time for just one day.
- Etc.

By prompting users to choose between disabling all instances or just the next occurrence, the app can ensure that users maintain their desired routine while accommodating their changing needs.

**Use case**
As a user who sets recurring alarms for weekdays, I often forget to turn off my alarms for holidays or other special occasions. Thus, having the option to disable only the next occurrence of the alarm would provide greater flexibility. Furthermore, the app could recognize holidays and suggest disabling the alarm for just that day.

**Describe alternatives you've considered**
One alternative could be to manually turn off the alarm for each special occasion, but this is cumbersome and easy to forget (and forget to turn back on again).

**Comment by BlackyHawky** [comment]
@y-r-v 
Thanks for the compliments. I'm glad you like the changes made to the application. 😉

About the proposed improvement, don't you think it's related to #4 ?

However, perhaps I could change the list in the _"Notification reminder"_ setting ? (I don't really like the current list).
For example, the list could be: `30 minutes / 1 hour / 2 hours / 4 hours / 6 hours / 12 hours`

By doing this, we could cancel the next alarm from notification.

What do you think of this?

**Comment by y-r-v** [comment]
@BlackyHawky 

Hello!

I believe this is a different issue. While #4 focuses on *creating* an alarm on a specific date, my suggestion is to add the option to "Skip alarm on the next day."

To give you a more straightforward and clearer suggestion, I imagined something like this:

1. The user has a recurring alarm (e.g., Monday to Friday).
2. For a particular reason, the user wants to skip just the next day (it could be a day off or a holiday, for example).
3. When the user clicks to deactivate the alarm, a pop-up could appear with the following message:

   **Deactivate recurring alarm?**
   - Ignore tomorrow
   - Deactivate recurring alarm
   - Cancel

This pop-up would only appear for recurring alarms.
4. The alarm would skip just the next day and **reactivate** itself on the next.

What do you think? In my opinion, this does not add friction and helps us deactivate the alarm for just one day without the need to manually reactivate it afterwards (which is prone to being forgotten).

**Comment by BlackyHawky** [comment]
I understand exactly what you want. The only question I have is why add a button or something to do this when we can already do it from the notification of the next upcoming alarm... 🤔

**Comment by BlackyHawky** [comment]
With the commit indicated above, you'll be able to do whatever you want from the upcoming alarm notification, which will be much simpler and won't even require you to open the application.

**Comment by human84288** [comment]
just want to leave a comment here for anyone trying to replicate the functionality from the OP, which is also the only thing about my original default alarm app that i used to prefer over this one. (i like to keep my notifications clean, and i might want to temporarily delay an alarm earlier than 12 hours before the alarm, which is the soonest you can display an alarm's notification for)

if you simply enable the option "display dismiss button as soon as alarm is enabled" within the alarm options, then you can disable any alarm at any time. and, if you disable a recurring alarm it will simply disable the next iteration of that alarm, which is exactly the functionality i wanted.
