### ISSUE TITLE
Alarms sometimes do not trigger, or nonexistent alarms do trigger

### ISSUE THREAD

**Issue by raxod502** [BlackyHawky/Clock#12]
I've noticed two unexpected behaviors that occur from time to time when using this clock app:

* Sometimes an alarm I have configured does not ring at the expected time, and the notification saying that there is an upcoming alarm persists, now referring to a time that is in the past.
* Sometimes an alarm that no longer exists will ring. For example, yesterday evening I changed my 7:15am alarm to 8:15am. However, this morning it still rang at 7:30am, despite a notification saying the upcoming alarm was at 8:15am. (It did not ring at 8:15am.)

Due to the similarity I suspect these behaviors might be caused by the same bug.

I am using Android 12 on the Pixel 3a, rooted, with battery optimization disabled for the clock app.

<details>
<summary>Screenshot, note that alarm is still listed as "upcoming at 6:50" despite it being 6:58 by now and no alarm having gone off</summary>

![image](https://user-images.githubusercontent.com/6559064/189541008-a37dcde0-cd07-4e4d-bc30-90c52e244527.png)

</details>

**Comment by BlackyHawky** [comment]
Due to recent changes, I'm closing this issue.
To be reopened if the error reappears.
