### ISSUE TITLE
Timer sorting in landscape mode

### ISSUE THREAD

**Issue by don-dolarson** [BlackyHawky/Clock#125]
**Describe the bug**

With the latest update, the new timers sorting functionality by dragging them works only in portrait mode.

**To Reproduce**

**Expected behavior**

**Screenshots**

**App version**

2.9
**Device (please complete the following information):**
 - Model:  OnePlus 5T
 - OS:  LineageOS 20

**Additional context**

**Comment by BlackyHawky** [comment]
@don-dolarson 
Oops. I did the right thing for tablets but totally forgot to do it for phones in landscape. 😬

I'll fix that shortly. 😉
