### ISSUE TITLE
Possible merger with new-clock repo

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [BlackyHawky/Clock#13]
I think this project could be merged with your new-clock repository, and add some scripts to provide different compile options, [Librera Reader](https://github.com/foobnix/LibreraReader) is already have this model.

**Comment by qw123wh** [comment]
That's what I would like to do but I honestly don't know how to do it. The package name is the same.  However, the signatures are different.  You could change the name of the package but it would not make sense, you would have to create 3 clock apps. If you can do it or someone can do it even with a PR I would be very grateful

**Comment by licaon-kter** [comment]
Umm, which app should remain in the end? From which repo codebase?

**Comment by cicciobellohalabua2** [comment]
@licaon-kter this https://github.com/qw123wh/new-clock
