### ISSUE TITLE
Digital time picker: confirm with keyboard Enter key

### ISSUE THREAD

**Issue by ltguillaume** [BlackyHawky/Clock#133]
**Is your feature request related to a problem? Please describe.**

When using the digital time picker, pressing the Enter key after setting the time (the key already changes to a checkmark) doesn't set the time and closes the dialog, but just closes the keyboard.

**Describe the solution you'd like**

When the time is set and keyboard closes to confirm it, set the time and close the timer picker, too.

**Comment by BlackyHawky** [comment]
The application uses `MaterialTimePicker` extracted from the _Material Components library_.
Therefore, this improvement should be requested [here](https://github.com/material-components/material-components-android).

**Comment by ltguillaume** [comment]
For reference: https://github.com/material-components/material-components-android/issues/4800

**Comment by ltguillaume** [comment]
1. Issue https://github.com/material-components/material-components-android/issues/4800 has never been responded to, so it's unlikely these issues will ever be addressed.
2. I see the **timer** input is completely different (is it custom?) and would be a perfect alternative for (and look even more integrated than) `MaterialTimePicker` if the seconds field could be removed, would this be an option? It's already virtually the same as https://github.com/BlackyHawky/Clock/issues/132#issuecomment-3066043677.

**Comment by BlackyHawky** [comment]
@ltguillaume 
Oops; there was a mix-up in our comments; this thread is about the `MaterialTimePicker`, not the `MaterialDatePicker`.
I corrected our comments.

1. Your created issue was addressed to a person so you still have to wait...
2. What exactly are you talking about? Can you provide a screenshot please?

**Comment by ltguillaume** [comment]
1. True, sorry about that, I just copied the term from your post.
2. I meant the time picker for timers:
    ![Image](https://github.com/user-attachments/assets/bd1593ed-af73-4e79-bd4b-922241c0ab6e)
    Lose the seconds and you're done.
    (Well, maybe add a button for 30min, like below)
    <img width=270 src="https://github.com/user-attachments/assets/e0757450-c31e-42c2-a994-d2ff77857340">

**Comment by BlackyHawky** [comment]
I absolutely do not plan to replace the `MaterialTimePicker` in digital mode with what you propose.
You must therefore wait until your [issue](https://github.com/material-components/material-components-android/issues/4800 ) is resolved.

Finally, let's be honest, pressing the OK button in the dialog box does not require considerable effort...

**Comment by ltguillaume** [comment]
The main problem is that the keyboard often doesn't show up at all until you click on a field, which is not as intended.

The OK button is located at the top half of the screen, so yes, not being able to use Enter to confirm suddenly requires two hands to input a time or a careful shift of the hand toward to top of the screen, which is a considerable effort.

**Comment by BlackyHawky** [comment]
> The main problem is that the keyboard often doesn't show up at all until you click on a field, which is not as intended.

Maybe it's your keyboard, because it's never happened to me.

> The OK button is located at the top half of the screen, so yes, not being able to use Enter to confirm suddenly requires two hands to input a time or a careful shift of the hand toward to top of the screen, which is a considerable effort.

With a 30-centimeter screen, perhaps...

In any case, it's not because of the app, so this isn't the right place to say that.

**Comment by ltguillaume** [comment]
> > The main problem is that the keyboard often doesn't show up at all until you click on a field, which is not as intended.
> 
> Maybe it's your keyboard, because it's never happened to me.

That's of course a possibility. I'm using HeliBoard. Will see if this'll change with another keyboard app.

**Comment by BlackyHawky** [comment]
> That's of course a possibility. I'm using HeliBoard. Will see if this'll change with another keyboard app.

I also use Heliboard and haven't had any problems.

What's certain is that I didn't specify anything in the code. The keyboard opens automatically, so if you encounter any problems, you'll need to open another issue [here](https://github.com/material-components/material-components-android).

**Comment by ltguillaume** [comment]
Concerning the keyboard not showing up, this is what happens every time, unless I already visited the Clock app very recently:
```
--------- switch to events
00:35:08.293 22686 22686 I viewroot_draw_event: [window=VRI[DeskClock],event=reportDrawFinished seqId=0]
--------- switch to main
00:35:08.339 22686 22686 D InsetsController: hide(ime(), fromIme=false)
00:35:08.339 22686 22686 I ImeTracker: com.best.deskclock:27299e19: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN
--------- switch to events
00:35:09.723 22686 22686 I viewroot_draw_event: [window=VRI[DeskClock],event=reportDrawFinished seqId=0]
--------- switch to main
00:35:09.731 22686 22686 I ImeTracker: com.best.deskclock:4a999094: onRequestShow at ORIGIN_CLIENT reason SHOW_SOFT_INPUT fromUser false
00:35:09.734 22686 22686 I ImeTracker: com.best.deskclock:4a999094: onFailed at PHASE_CLIENT_VIEW_SERVED
00:35:09.734 22686 22686 W InputMethodManager: Ignoring showSoftInput() as view=com.google.android.material.textfield.TextInputEditText{5b9242 VFED..C.. .F...... 0,0-252,210 #d aid=1073741830} is not served.
00:35:09.736 22686 22686 E com.best.deskclock: Invalid resource ID 0x00000000.
00:35:09.742 22686 22686 I AssistStructure: Flattened final assist data: 9612 bytes, containing 2 windows, 77 views
00:35:09.779 22686 22686 I ImeTracker: com.best.deskclock:972bea65: onRequestShow at ORIGIN_CLIENT reason SHOW_SOFT_INPUT fromUser false
00:35:09.779 22686 22686 I ImeTracker: com.best.deskclock:972bea65: onFailed at PHASE_CLIENT_VIEW_SERVED
00:35:09.779 22686 22686 W InputMethodManager: Ignoring showSoftInput() as view=com.google.android.material.textfield.TextInputEditText{5b9242 VFED..C.. .F...... 0,0-252,210 #d aid=1073741830} is not served.
--------- switch to events
00:35:11.165 22686 22686 I view_enqueue_input_event: [eventType=Motion - Cancel,action=com.best.deskclock/com.best.deskclock.DeskClock]
```

Procedure is simply:
1. Open Clock app
2. Press the [+] button to add an alarm
3. See that the keyboard doesn't show up

In contrast, this is what the logcat dump looks like when the keyboard **is** shown:
```
00:46:02.335 22686 22686 I viewroot_draw_event: [window=VRI[DeskClock],event=reportDrawFinished seqId=0]
--------- switch to main
00:46:02.361 22686 22686 D InsetsController: hide(ime(), fromIme=false)
00:46:02.361 22686 22686 I ImeTracker: com.best.deskclock:a3fec756: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN
00:46:02.387 22686 22686 I ImeTracker: system_server:1c1cbd04: onCancelled at PHASE_CLIENT_ON_CONTROLS_CHANGED
--------- switch to events
00:46:03.524 22686 22686 I viewroot_draw_event: [window=VRI[DeskClock],event=reportDrawFinished seqId=0]
--------- switch to main
00:46:03.530 22686 22686 I ImeTracker: com.best.deskclock:8b3c9b8b: onRequestShow at ORIGIN_CLIENT reason SHOW_SOFT_INPUT fromUser false
00:46:03.530 22686 22686 I ImeTracker: com.best.deskclock:8b3c9b8b: onFailed at PHASE_CLIENT_VIEW_SERVED
00:46:03.530 22686 22686 W InputMethodManager: Ignoring showSoftInput() as view=com.google.android.material.textfield.TextInputEditText{f6ec816 VFED..C.. .F...... 0,0-252,210 #1b aid=1073741905} is not served.
00:46:03.530 22686 22686 E com.best.deskclock: Invalid resource ID 0x00000000.
00:46:03.532 22686 22686 I AssistStructure: Flattened final assist data: 9612 bytes, containing 2 windows, 77 views
00:46:03.604 22686 22686 I ImeTracker: com.best.deskclock:b1358306: onRequestShow at ORIGIN_CLIENT reason SHOW_SOFT_INPUT fromUser false
00:46:03.604 22686 22686 D InsetsController: show(ime(), fromIme=false)
--------- switch to system
00:46:03.609 22686 22686 D InsetsController: Setting requestedVisibleTypes to -1 (was -9)
00:46:03.712 22686 23599 W InteractionJankMonitor: Initializing without READ_DEVICE_CONFIG permission. enabled=false, interval=1, missedFrameThreshold=3, frameTimeThreshold=64, package=com.best.deskclock
--------- switch to events
00:46:03.714 22686 23600 I jank_cuj_events_begin_request: [CUJ Type=80,Tag=0@0@com.best.deskclock]
00:46:03.920 22686 23600 I jank_cuj_events_end_request: [CUJ Type=80]
--------- switch to main
00:46:03.920 22686 22686 I ImeTracker: com.best.deskclock:b1358306: onShown
```

**Comment by BlackyHawky** [comment]
@ltguillaume 
Have you tried with another keyboard? 

I stopped using Heliboard a while ago and now use the FUTO keyboard.
As I already told you, it's impossible to reproduce on my three Android 9/12 and 14 devices.

**Comment by ltguillaume** [comment]
Yep, sorry, I tried with 3 other keyboard apps now (AOSP, Fossify, Keepass) and can't reproduce it with those.

**Comment by BlackyHawky** [comment]
@ltguillaume 
I was sure of it. It's up to you if you want to use another keyboard...

**Comment by ltguillaume** [comment]
https://github.com/Helium314/HeliBoard/issues/2075
