### ISSUE TITLE
ascending alarm volume

### ISSUE THREAD

**Issue by Joppla** [BlackyHawky/Clock#135]
Hi
Is it possible to make the alarm volume ascending. That the start it for example 10% of the maximum and higher up every x seconds with stamps of 10%.

Thanks

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Use case**

**Describe alternatives you've considered**

**Additional context**

**Comment by BlackyHawky** [comment]
I don't see the benefit of making this kind of change compared to the _Gradually increase volume_ setting.

**Comment by Joppla** [comment]
You are completely right, before I didn't find that option, now I found. Thx.
