### ISSUE TITLE
Adding an edit mode and a view mode, Or holding down a timer to delete it

### ISSUE THREAD

**Issue by Fuoxden** [BlackyHawky/Clock#138]
**Is your feature request related to a problem? Please describe.**
I have been using the app for a bit, It works super good! Its nice and looks really pretty, but there is one problem that drives me crazy! I don't really know how to describe it so i will show you some images i made to illustrate my problem:

<img width=200 src="https://github.com/user-attachments/assets/8a694dc3-0449-4d80-85ba-3e87ae16036a">

You see the X buttons? Well, They delete your timer, i have fat fingered and accidentally hit the X buttons so many times, it is really frustrating, i have a few solutions!

**Describe the solution you'd like**

Instead of having an X button to get rid of timers, how bout holding down on the timer to open a menu to have the option to delete, Maybe there could be more options, Maybe a share timer, Export, or even a duplicate button!

**Use case**
I believe it would stop people like me, from fat fingering the delete button, it would probably open up opportunities to add new features in the future!

**Describe alternatives you've considered**

You could have a toggle in the settings to turn off the X's

**Additional context**

I think i explained myself well enough! i don't believe i need to add Additional context

**Conclusion**

I believe this would make the app more usable and stop people from fat fingering or accidentally hitting the X buttons, I hope you consider adding what i have Described! Cheers mate!

**Comment by BlackyHawky** [comment]
@Fuoxden 
I would like to know if adding a setting in the Timers settings to display the timers in "extended" or "compact" mode would suit you?
In expanded view, you will no longer touch the delete button.

**Comment by Fuoxden** [comment]
I didn't think of that, I think a compact/extended mode would be great! I think that would be nice, thank you if you do end up going with an compact/extended mode!

**Comment by BlackyHawky** [comment]
@Fuoxden 
Can you test the apk below and tell me if the new setting added to the Timers settings suits you?

[Clock_2.11_beta-debug.zip](https://github.com/user-attachments/files/17910314/Clock_2.11_beta-debug.zip)

**Comment by Fuoxden** [comment]
Of course! I would be Honored to try it! I will try it in a bit when I'm done walking my dogs

**Comment by Fuoxden** [comment]
Okey, my thoughts on the new setting, I think it looks nice, I do have to say, it doesn't really look compact, the original default style looks compact compared to the "compact" mode, also, I believe it has the same problem, if your trying to open the setting or even just not paying attention you could hit the x/delete button like what I said in the original post, but, I do have an idea that I think would fix my problems with the app, you know the alarms? I think I will show you with a picture:

<img width=200 src="https://github.com/user-attachments/assets/add66f75-bd21-40f7-9769-e06831a4ebb9">

You see the delete and duplicate button? You first click the dropdown and then it shows you all the options, like changing the alarm sound, vibration, etc, why dont you do the same with the timers? And have it turned on by a toggle in the settings?

**Comment by BlackyHawky** [comment]
@Fuoxden 
> why dont you do the same with the timers?

I wouldn't do the same thing because it would require a lot of work.

However, a much simpler alternative would be to display a dialog box when the user clicks on this button, asking the user if he's sure he wants to delete the timer.

Obviously, the user will have the choice to display this dialog box or not in the Timers settings.

**Comment by Fuoxden** [comment]
Ah okay! You know what? That sounds like a much simpler Solution! I think that would be good!

**Comment by BlackyHawky** [comment]
Great. I'll provide you a new apk to test this tomorrow. I need to sleep because it's very late at home 😅

**Comment by Fuoxden** [comment]
I understand! Thank you! I really like what your doing with this clock app! One of my favorite clock apps out there!

**Comment by Fuoxden** [comment]
Oh yeah, also, I do like that compact mode even if its not really compact, I would love to have that stay as well, anyways bye! Have a good day

**Comment by BlackyHawky** [comment]
@Fuoxden 
As promised, here's the new apk.
You'll be able to display a confirmation dialog before deleting a timer in the Timers settings.

I think that's the best solution and that's what I'll adopt.

[Clock_2.11_beta-debug.zip](https://github.com/user-attachments/files/17917452/Clock_2.11_beta-debug.zip)

**Comment by Fuoxden** [comment]
I think this is perfect! Thank you! Also sorry for the late response, I just woke up

**Comment by BlackyHawky** [comment]
@Fuoxden 
No worries. I'm in no hurry 😉
Thanks for your feedback.
