### ISSUE TITLE
Ringtone preview in Alarms settings won't stop

### ISSUE THREAD

**Issue by ghost** [BlackyHawky/Clock#147]
**Describe the bug**

When I want to change the Volume in the Settings, then the Sound don't stop, until I closed the App or if I go back. I hope this can be fixed

**To Reproduce**

**Expected behavior**

To make it louder and that the Sound stops after a short time, without me needing to go back or closing the App.

**Screenshots**

**App version**

Version 2.10

**Device (please complete the following information):**
 - Model:  Xiaomi Poco X3 NFC
 - OS:  Android 14

**Additional context**

**Comment by BlackyHawky** [comment]
@PrivacyAndSecurity 
Very strange; unable to reproduce this on my 3 devices (Huawei - Android 12 / Samsung - Android 14 / Redmi Note 5 - Android 9)

Edit: Tested on  Xiaomi Poco F5 Pro with Android 14 unable to reproduce this bug...

**Comment by BlackyHawky** [comment]
@PrivacyAndSecurity 
Can you please test the apk attached below?

[Clock_2.10.1-debug.zip](https://github.com/user-attachments/files/17906722/Clock_2.10.1-debug.zip)

**Comment by ghost** [comment]
> @PrivacyAndSecurity Very strange; unable to reproduce this on my 3 devices (Huawei - Android 12 / Samsung - Android 14 / Redmi Note 5 - Android 9)

Sorry for the late reply. Oh, I understand. Really strange, I agree. 

> Edit: Tested on Xiaomi Poco F5 Pro with Android 14 unable to reproduce this bug...

Oh! I tried to do a Sceen Recording with 3 different Apps but the Sound just will not record, but I don't know why. And same for my volume Bar of my Phone, that don't get showed in the Video too...I wish I could explain it with the Video, but let me try to explain the Steps to reproduce here:

1. Go to Settings and then Alarm in the Clock App
2. Click on the volume bar, for example to the middle and then go one page back or click on the Page to see your open Apps at the moment. The Sound of this Volume Bar don't stop immediately if you go back or to the open Apps Page. It takes a few Seconds and sometimes I need to close the App entirely to stop it.

I hope I could explain it approximately. It's not a big thing but I wish that it could be fixed.

**Comment by ghost** [comment]
> @PrivacyAndSecurity Can you please test the apk attached below?
> 
> [Clock_2.10.1-debug.zip](https://github.com/user-attachments/files/17906722/Clock_2.10.1-debug.zip)

I did, but it did not change, sadly.

**Comment by BlackyHawky** [comment]
@PrivacyAndSecurity 
Can you please test the new apk again?
On my devices, the ringtone preview lasts 5 seconds and stops immediately if you quit the activity or if the application is minimized.
So this improves on what already exists.

[Clock_2.11_beta-debug.zip](https://github.com/user-attachments/files/17951407/Clock_2.11_beta-debug.zip)

**Comment by ghost** [comment]
> @PrivacyAndSecurity Can you please test the new apk again? On my devices, the ringtone preview lasts 5 seconds and stops immediately if you quit the activity or if the application is minimized. So this improves on what already exists.
> 
> [Clock_2.11_beta-debug.zip](https://github.com/user-attachments/files/17951407/Clock_2.11_beta-debug.zip)

Okay, I did test it now and I agree that it lasts 5 Seconds. But on my Phone it does not stop if I minimize the Application. But I noticed one good thing that you did. It stops immediately, when I go back inside of the App. Meaning when I click on going back in the App, the Sound stops immediately. The only thing left is, when I minimize it does not stop. If that will be fixed, then it would be perfect.

**Comment by BlackyHawky** [comment]
@PrivacyAndSecurity 
This is due to Xiaomi because they have tighter restrictions on background apps... It's really annoying...

Maybe you need to check your phone's system settings in: Settings > Battery > Manage background apps (or something very similar) and add the app to the list of unrestricted apps.

I don't know what else to do, especially without having a device like yours.

**Comment by ghost** [comment]
> @PrivacyAndSecurity This is due to Xiaomi because they have tighter restrictions on background apps... It's really annoying...

Oh! I agree, it just makes no sense.

> Maybe you need to check your phone's system settings in: Settings > Battery > Manage background apps (or something very similar) and add the app to the list of unrestricted apps.

I had this enabled already.

> I don't know what else to do, especially without having a device like yours.

No Problem, I totally understand that! Thank you so much for everything! I don't know if it is a Xiaomi Problem or because I use LineageOS and they eventually have restricted it too...I'm not sure about that. But anyways, how it is now, is good I think. Because even tho it don't stop when I minimize it, now I can just go back and it is fixed this way too. So everything good, I would say. Thank you for the effort and taking time. It truely means, that you take Feedback serious and try to do your best, which I appreciate a lot! Because I did not experience that a lot. And I used many Apps, even big Open Source Apps, where the wishes or Feedback was no taken serious. Having Developers who are friendly and open for Feedback or wishes, is one of the best feeling for the Users, because they know that this App has big potential. Because it is open to all of the good Features to implement.

**Comment by BlackyHawky** [comment]
> I don't know if it is a Xiaomi Problem or because I use LineageOS

I didn't know you were using LineageOS on your device! Maybe this is also the source of the problem!
Maybe you could open an issue for the LineageOS DeskClock application on Gitlab (link [here](https://gitlab.com/LineageOS/issues/android/-/issues)).

> ... I can just go back and it is fixed this way too. So everything good, I would say

I will therefore validate my modification as it is. 😉

> Thank you for the effort and taking time. It truely means, that you take Feedback serious and try to do your best, which I appreciate a lot! Because I did not experience that a lot. And I used many Apps, even big Open Source Apps, where the wishes or Feedback was no taken serious. Having Developers who are friendly and open for Feedback or wishes, is one of the best feeling for the Users, because they know that this App has big potential. Because it is open to all of the good Features to implement.

Thank you very much for your comment. I appreciate it very much. ♥
Indeed, I do my best to try to satisfy as many users as possible, especially since I never studied code at school and it is not my job at all. 😅
In any case that doesn't stop me from trying to resolve some inconveniences and also to bring new features to the application.

**Comment by ghost** [comment]
> > I don't know if it is a Xiaomi Problem or because I use LineageOS
> 
> I didn't know you were using LineageOS on your device! Maybe this is also the source of the problem! Maybe you could open an issue for the LineageOS DeskClock application on Gitlab (link [here](https://gitlab.com/LineageOS/issues/android/-/issues)).

True! I missed to say that. I agree, it really could be! Okay, I did that now.

> > ... I can just go back and it is fixed this way too. So everything good, I would say

> I will therefore validate my modification as it is. 😉

Okay :-)

> > Thank you for the effort and taking time. It truely means, that you take Feedback serious and try to do your best, which I appreciate a lot! Because I did not experience that a lot. And I used many Apps, even big Open Source Apps, where the wishes or Feedback was no taken serious. Having Developers who are friendly and open for Feedback or wishes, is one of the best feeling for the Users, because they know that this App has big potential. Because it is open to all of the good Features to implement.
> 
> Thank you very much for your comment. I appreciate it very much. ♥ Indeed, I do my best to try to satisfy as many users as possible, especially since I never studied code at school and it is not my job at all. 😅 In any case that doesn't stop me from trying to resolve some inconveniences and also to bring new features to the application.

No problem, your welcome! :)
That's so nice of you and I can understand the difficulty too. And yea, that's so true too :)
