### ISSUE TITLE
Can't stop alarm with swipe

### ISSUE THREAD

**Issue by woj-tek** [BlackyHawky/Clock#148]
**Describe the bug**
When alarm sounds, swiping it doesn't work - it still emits the sound and after a couple of seconds system pop-up shows that app is not responding with option to wait or kill it

**To Reproduce**
happens randomly

**Expected behavior**
Alarm should just stop like in previous versions

**Screenshots**
n/a

**App version**
2.10 / f-droid

**Device (please complete the following information):**
 - Model: Samsung Galaxy a52s 5g
 - OS: Android 14

**Comment by BlackyHawky** [comment]
@woj-tek 
Really sorry for this inconvenience; I am closing this topic because it is a duplicate of #136.

You can download the new version [here](https://github.com/BlackyHawky/Clock/releases/tag/2.10.1), where I unfortunately had to disable the "Set an alarm for a specific date" feature because it was at the root of this major bug.

I hope to find the solution soon.

**Comment by woj-tek** [comment]
Ah... f-droid is not up to date :)

sorry for the dup.

**Comment by BlackyHawky** [comment]
> Ah... f-droid is not up to date :)
> 
> sorry for the dup.

Don't worry.

That's what I don't like about F-Droid; the apps take too long to update...

**Comment by woj-tek** [comment]
There is also option to have own/custom repo (https://f-droid.org/en/repomaker/) or ask Izzy...

**Comment by BlackyHawky** [comment]
Thanks to @PrivacyAndSecurity who requested the addition on [GitLab](https://gitlab.com/IzzyOnDroid/repo/-/issues/668), it's already available [here](https://apt.izzysoft.de/fdroid/index/apk/com.best.deskclock).

I didn't even know about it 😅

I'll update the Readme.

Thank you @PrivacyAndSecurity 😉

**Comment by woj-tek** [comment]
LOL, me neither nor I did notice it on the list :D Just backed up, uninstalled and installed from Izzy :)

BTW. Just noticed that backup doesn't store alarms/timers/cities|timezones :(

**Comment by BlackyHawky** [comment]
BTW. Just noticed that backup doesn't store alarms/timers/cities|timezones :(

Currently, this is normal. An issue is already open about this.

**Comment by woj-tek** [comment]
This one: https://github.com/BlackyHawky/Clock/issues/130 ? (maybe add "backup" to the title so it would be easier to discover?) :)

**Comment by ghost** [comment]
> Thanks to @PrivacyAndSecurity who requested the addition on [GitLab](https://gitlab.com/IzzyOnDroid/repo/-/issues/668), it's already available [here](https://apt.izzysoft.de/fdroid/index/apk/com.best.deskclock).
> 
> I didn't even know about it 😅

I can imagine =}

> I'll update the Readme.
> 
> Thank you @PrivacyAndSecurity 😉

No problem, your welcome! :) 
Always again :-)
I need to thank you, because of your nice App, which has really good Features! :)
