### ISSUE TITLE
Volume Bar

### ISSUE THREAD

**Issue by ghost** [BlackyHawky/Clock#150]
**Describe the bug**

The Volume Bar inside of the App changes, when I change the Volume Bar from my Phone itself. I wish that I could set the Volume Bar inside of the App and that it don't change with my Phones Volume Bar.

**To Reproduce**

**Expected behavior**

That the Volume Bar inside of the App stays always how I did set it and that it don't change with my Phones Volume Bar.

**Screenshots**

I tried 3 Screen Recorders but it sadly did not record my Phones Volume Bar at the right side. 

**App version**

2.10.1

**Device (please complete the following information):**
 - Model:  Xiaomi Poco X3 NFC
 - OS:  Android 14 with LineageOS 21

**Additional context**
<!-- Add any other context about the problem here. --
It is not a big thing but I wish that this could be changed, that my Alarm Volume Bar always stay at a point, even if my Phones Volume Bar is not this high. Because it could happen that I forgot to make my Phones Volume Bar higher. And if it is already set inside of the App, then I guess even if I forgot to make it higher in my Phones Volume Bar, then it stays higher always. I hope that I could explain it approximately.

**Comment by BlackyHawky** [comment]
This is not a problem but normal behavior.
Indeed, the volume of the app's alarms corresponds to the volume of the alarms managed by the Android system.
I don't plan to change this behavior, whose code is (almost) that of [AOSP Deskclock](https://android.googlesource.com/platform/packages/apps/DeskClock/+/refs/heads/main/src/com/android/deskclock/settings/AlarmVolumePreference.kt).

**Comment by ghost** [comment]
Oh okay, thank you for telling. And I can understand that totally, of course.
