### ISSUE TITLE
Specify "USE_EXACT_ALARM" permission in manifest?

### ISSUE THREAD

**Issue by secretmango** [BlackyHawky/Clock#151]
Android has a permission for apps to set alarms and events or something.

If that is used, the time when the next alarm will ring, is displayed on the lockscreen.

Also, alarms always work.

This is not the case for this clock, and I am pretty certain that alarms dont ring reliably.

I think the permission is `USE_EXACT_ALARM`

https://developer.android.com/about/versions/14/changes/schedule-exact-alarms

**Comment by BlackyHawky** [comment]
Hi,

Do not indicate the `Bug` label if you have not encountered a bug on your device; it can mislead users. Especially since the title you had written clearly indicated that the alarm does not sound in general when this is not the case.

Also, it is better to use the template in case of a bug.

I'll take a look later because until proven otherwise, it works fine on my device with Android 14.

**Comment by secretmango** [comment]
The bug is that the alarm does not register as an alarm and doesnt reliably go off.

This is how it should look like on the lockscreen.

<img width=200 src="https://github.com/user-attachments/assets/04307105-a944-4142-ac1a-03071dbb1211">

I am using Android 15, which may be a difference here. I am not sure if the bug goes further than the missing display, I will check.

**Comment by BlackyHawky** [comment]
@secretmango 
When you say _"doesnt reliably go off"_, does that mean that **no** alarm goes off?

Moreover, you mean you can display this app's widget on lock screen?

What model is your device? Do you use an alternative ROM?

Note: Currently, the maximum SDK for this application is 34, so perhaps some adjustments need to be made for Android 15.

**Comment by secretmango** [comment]
Hi there. Not sure why, but now it is working. Alarms are also working, also in BFU state.

I am on latest GrapheneOS, based on Android 15.

Got an update recently, now the clock alarm is showing too. Before, the stock GrapheneOS clock (old AOSP base) also showed it.

I think this is fixed.

**Comment by BlackyHawky** [comment]
Great news! Thanks for updating this topic.
