### ISSUE TITLE
Change `X` icon to trash icon on timers screen

### ISSUE THREAD

**Issue by woj-tek** [BlackyHawky/Clock#154]
**Is your feature request related to a problem? Please describe.**

Change icon in timers list to trash/bin icon from `X`. When timer is running one could quickly tap x to collapse it and instead it would delete the timer

**Comment by BlackyHawky** [comment]
@woj-tek 
I am not at all against this request for improvement.
Since this is easy to do, I will publish the commit very quickly.

**Comment by woj-tek** [comment]
Thank you!
