### ISSUE TITLE
Alarm just doesn't work sometimes

### ISSUE THREAD

**Issue by gordon-fr33man** [BlackyHawky/Clock#157]
_Describe the bug_
I have a very strange problem for which I unfortunately cannot provide much information. At irregular intervals, my set alarm clocks suddenly stop working. Up to and including the day before yesterday, my alarm clock woke me up perfectly at 06:30. Since yesterday, it has simply remained silent without me having changed anything in the alarm clock or the app. There was no update to the operating system or anything similar at the time in question. I found out that reinstalling the app helps, but unfortunately I can't say any more than that.

_App version_
2.10 (installed 2.10.1 today after waking up, so I can't tell if that makes a difference)

_Device_
 - Model: Fairphone 4
 - OS: Android 13

**Comment by BlackyHawky** [comment]
@gordon-fr33man 
Hi,

There was a major bug in version 2.10 about alarms, so it is strongly recommended to use version 2.10.1.

I'm closing this topic but don't hesitate to open another issue if it concerns version 2.10.1.
