### ISSUE TITLE
Random crash after device reboot

### ISSUE THREAD

**Issue by ABJ4403** [BlackyHawky/Clock#166]
**Describe the bug**
Random crash popup after device rebooted

**To Reproduce**
Just reboot the device, or maybe add clock widget

**Expected behavior**
Simply shouldn't show crash popup

**App version**
<will fill this later, iirc its before the newer release>

**Device**
 - OS: LineageOS 14.1, Android 7.1.2

**Additional context**
```java
java.lang.RuntimeException: Unable to start receiver com.best.alarmclock.VerticalDigitalAppWidgetProvider: java.lang.IllegalArgumentException: Log tag "VerticalDigitalWidgetProvider" exceeds limit of 23 characters
	at android.util.Log.isLoggable(Native Method)
	at com.best.deskclock.LogUtils$Logger.isInfoLoggable(LogUtils.java:69)
	at com.best.deskclock.LogUtils$Logger.i(LogUtils.java:99)
	at com.best.alarmclock.VerticalDigitalAppWidgetProvider.onReceive(VerticalDigitalAppWidgetProvider.java:351)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3065)
	... 8 more
```

I made this report at midnight (23.05 PM) and with my primary device (the 2nd device where i experienced the bug, ita outta battery bcz its a really old phone), i dont have time to properly fill all the report details, will do so later :v

**Comment by BlackyHawky** [comment]
@ABJ4403 
With the log you've provided, it seems to come from the log name indicated [here](https://github.com/BlackyHawky/Clock/blob/9613c72d902c181db905b0c9b88d48c8afff8ba7/app/src/main/java/com/best/alarmclock/standardwidgets/VerticalDigitalAppWidgetProvider.java#L84).

If I'm right, you should also encounter the bug with other widgets, such as the Material You digital widget and the Material You Next Alarm widget. If this is the case, it should be very easy to resolve.

Can you please test with these 2 other widgets?

**Comment by ABJ4403** [comment]
Damn accidentally closed the issue (im typing this on phone btw)

I'm currently outside, didnt have the 2nd device on hand, but i think the fix is as simple as making "VerticalDigitalWidgetProvider" shorter (maybe "vDgtlWdgtProvider", its 17 characters long, so maybe those wont trigger the error), as suggested by the error it says cant use more than 23 characters

**Comment by BlackyHawky** [comment]
@ABJ4403 
Just to be sure before validating the commit, can you please test the apk below?

[Clock_2.12_beta-debug.zip](https://github.com/user-attachments/files/18198055/Clock_2.12_beta-debug.zip)
