### ISSUE TITLE
disabling alarm bug

### ISSUE THREAD

**Issue by maxongshD** [BlackyHawky/Clock#18]
in window for disabling alarm bug. 
alarm window not  full cover display. i'm show this in screenshot. please, fix it.

<img width=200 src="https://github.com/qw123wh/new-clock-fdroid/assets/142055169/49af8f3b-e114-4ee7-aae8-ba43b2603565">

**Comment by BlackyHawky** [comment]
Due to recent changes, I'm closing this topic.

To be reopened if the error reappears.
