### ISSUE TITLE
FR: "essential permission" guide should be on only after first start

### ISSUE THREAD

**Issue by woj-tek** [BlackyHawky/Clock#27]
**Is your feature request related to a problem? Please describe.**
A toast with "essential permissions are missing" shows up (and hides navigation buttons) on each start.

**Describe the solution you'd like**
It should be show only on first launch and then have possibility to followup from the settings.

**Use case**
I don't grant DND permission as I don't see it necessary (I don't use this clock app as alarm) and the pop-up doesn't make any sense on each opening of the app.

**Describe alternatives you've considered**
Granting the permission just to get rid of it but that's just a workaround. 

Downgrading to 1.2 is also considered.

**Additional context**
version 2.0

**Comment by BlackyHawky** [comment]
> I don't grant DND permission

In version 2.1, available [here](https://github.com/BlackyHawky/Clock/releases/tag/2.1) (on F-Droid, probably tomorrow), DND permission has been removed from the application.

> Granting the permission just to get rid of it but that's just a workaround.

Granting these permissions is necessary for the application to function properly; it is therefore normal for a message to appear to inform the user that some of them have not been granted. (Obviously, this only applies to essential permissions.)

It would be worse if there were no indication that essential permissions were not granted, and that the alarm was not triggered, for example. BTW, I'm sure that an issue would be opened asking for this request.

> Downgrading to 1.2 is also considered.

Of course, if you prefer the earlier version, you can always use version 1.2 available [here](https://github.com/BlackyHawky/Clock/releases/tag/1.2).
It will never be removed from this repository.

**Comment by woj-tek** [comment]
> In version 2.1, available [here](https://github.com/BlackyHawky/Clock/releases/tag/2.1) (on F-Droid, probably tomorrow), DND permission has been removed from the application.

Oh, ondeed I use f-droid version.



> Granting these permissions is necessary for the application to function properly; it is therefore normal for a message to appear to inform the user that some of them have not been granted. (Obviously, this only applies to essential permissions.)
> 
> It would be worse if there were no indication that essential permissions were not granted, and that the alarm was not triggered, for example. BTW, I'm sure that an issue would be opened asking for this request.

I agree that it's normal to inform the user but AFAIR most of the apps do the initial "welcome setup" and then after completing it don't bother user again. IMHO it's quite sensibe approach.

We can argue that for example "notifications" are essential but if somone just want a stopwatch with a screen always-on then the notifications are not essential and so on :-)

> Of course, if you prefer the earlier version, you can always use version 1.2 available [here](https://github.com/BlackyHawky/Clock/releases/tag/1.2).

Fdroid offers earlier versions so that's quite handy :-)

**Comment by BlackyHawky** [comment]
I understand your opinion better, but what's the point of downloading an alarm app just to use the stopwatch?

**Comment by woj-tek** [comment]
Hmm... I use SleepAsAnAndroid for ages now (10-15y?) and I use "Clock" (any flavours over the year) as a clock app (with timezones), timer and stopwatch (which I use quite often during the day). So all in all for me it's more a "clock" app than "alarmclock" (which I don't use at all in it, hence the suggestion to customise the sections) :-)

**Comment by BlackyHawky** [comment]
As discussed in #31 ans as mentioned [here](https://github.com/BlackyHawky/Clock/issues/31#issuecomment-2108279855), instead of the toast message, I will try to display a message which will only be present in the settings.
I'll keep you informed.

**Comment by woj-tek** [comment]
Great, thank you!
