### ISSUE TITLE
FR: Even darker UI - less element containers with solid grey background.

### ISSUE THREAD

**Issue by woj-tek** [BlackyHawky/Clock#29]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to remove/configure element container - either configure the color/border/background (and possibly set it to black to make it go away) or have and option to disable it.

I'm not particularly fond of MaterialYou design (de gustibus…) and I find previous UI (see screenshots https://f-droid.org/packages/com.best.deskclock/) much cleaner.

Considering that on AMOLED true black background is desired it would be nice to be able to remove as much of the grey-ish backgrounds as much as possible.

**Comment by BlackyHawky** [comment]
As you can imagine, it's very complicated to keep everyone happy with the design of an application... 😬

> I'm not particularly fond of MaterialYou design ... and I find previous UI ... much cleaner.

I personally prefer the new interface, which clearly separates each alarm, for example.

**Comment by woj-tek** [comment]
> As you can imagine, it's very complicated to keep everyone happy with the design of an application... 😬

I know. To my dismay I found out that current list of timers (instead of one per screen) is a result of a request #7 so yeah, people have different tastes :D

Some MaterialYou applications allows adjusting background colour (to have it darker). It would be awesome if one could only have a border instead of full fill background thus having the separation but less intense.

**Comment by BlackyHawky** [comment]
Even if I prefer the new interface, I'll try to implement your request. That's why I've left this topic open.

**Comment by BlackyHawky** [comment]
@woj-tek: Can you test the app version attached? I think I've met your expectations.

In the settings, I've added 2 options to show/hide backgrounds and show/hide background borders.
I'll wait for your feedback before merging my changes.

[Clock_2.1-debug.zip](https://github.com/BlackyHawky/Clock/files/15313196/Clock_2.1-debug.zip)

**Comment by woj-tek** [comment]
@BlackyHawky Looks awesome! Tiny comment - settings page doesn't follow it (I don't look too often there so less of an issue, just a matter of consistency) :-)

Thank you so much! <3

**Comment by BlackyHawky** [comment]
> Tiny comment - settings page doesn't follow it

Indeed, I forgot to mention it. 😬
I didn't manage to do it, but it can be done later.

In any case, I'm very happy to have met your expectations. 😁
