### ISSUE TITLE
Add option in settings to change theme

### ISSUE THREAD

**Issue by qw123wh** [BlackyHawky/Clock#3]
The options for the theme must be light / dark / system

**Comment by KrasnayaPloshchad** [comment]
I think this app is far less customizable than [Clock L](https://apkpure.com/clock-l/com.moblynx.clockl), and you probably need to do more works for this.

**Comment by Korb** [comment]
Judging by the lack of screenshots with a black theme on [the app page in F-Droid](https://f-droid.org/packages/com.best.deskclock/) , does the app still not support it?

**Comment by BlackyHawky** [comment]
Done with commits ecee78b + 5733587.
