### ISSUE TITLE
FR[/bug?] Timer doesn't show full-screen notification/overlay on top of other applications

### ISSUE THREAD

**Issue by woj-tek** [BlackyHawky/Clock#32]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a full-screen notification when timer is up. It works for when the screen is off but not if the screen is on and we are in other application.

It worked in version 1.2 in earlier versions of Android (AFAIR stopped after upgrading to Android 14)

**Comment by BlackyHawky** [comment]
Are you sure this is the right way to behave?
Indeed, if you're playing a game, for example, I'm not sure that showing the timer expired in full screen is a good thing...
Displaying the notification is enough.

**Comment by woj-tek** [comment]
> Are you sure this is the right way to behave?

I'm not sure and I don't feel confident enough to speak about whether it's right or wrong. For me, it's quite (very much) convenient though.



> Indeed, if you're playing a game, for example, I'm not sure that showing the timer expired in full screen is a good thing...

Well, I don't play on my mobile but this FR somewhat touches on the issue - I do want to be forcebily interrupted - I use timers to limit time I spend on mobile so so reading or whatnot, having this full-screen alarm (as before) was VERY helpful for that.

On the other hand if I use timer (cooking for example), full screen timer is very handy as I can easily disable it with my pinky as the "stop" button is immediatelly visible and easily accessible.

> Displaying the notification is enough.

Hmm... I disable virtually all "popup/baloon" notifications as I find them annoying AF - imagin reading something and you get constantly popup with the message over the stuff you read. For me icons in the notifications area are nough - if there is a new notification I get an icon so when I'm done with doing X I can check it/respond. I don't need to be constantly interrupted.

I tried enabling notifications/baloons for clock but still - they don't appear at all...

(I know, I may be a bit weird with use-cased 😅)

**Comment by BlackyHawky** [comment]
Impossible to reproduce the expected behavior with version 1.2 on Android 12 and 14.

**Comment by woj-tek** [comment]
I'll have to grab my old device (but it's in different location so most likely in 2 months…) to verify it because I'm not even sure how to downgrade current device…

**Comment by BlackyHawky** [comment]
> Impossible to reproduce the expected behavior with version 1.2 on Android 12 and 14.

Also impossible to reproduce the expected behavior with version 1.2 on Android 9.
I have doubts this was available on version 1.2...
3 different models, 3 different versions of Android and impossible to reproduce what you describe.

**Comment by BlackyHawky** [comment]
As I have no news and it is impossible to reproduce what is requested on several devices and several versions of Android, I am closing this issue.
