### ISSUE TITLE
Alarm list regression in 2.x

### ISSUE THREAD

**Issue by fs2597** [BlackyHawky/Clock#36]
**Describe the bug**

In 1.2, the list of alarms shows the days that each alarm repeats on.

In 2.1 (I skipped 2.0 because I don't check for updates that often) the list doesn't show this info. Instead, it shows some "turned off" text that duplicates the info already communicated by the toggle being in the "off" position.

This makes the list much less useful if I have to manually expand every one to figure out which one it is.

**To Reproduce**

1. Create 2 or more alarms and set them to repeat on different days.

2. Look at the alarms list.

3. Repeat and compare in both 1.2 and 2.1.

**Screenshots**

Old list with days:
<img src="https://github.com/BlackyHawky/Clock/assets/118265658/dce90864-c6cd-4a8e-ba7d-9224de85a66f" alt="Alarm list in 1.2" height="300"/>

New list missing days:
<img src="https://github.com/BlackyHawky/Clock/assets/118265658/faab3be9-6c5e-4e7f-ad99-d12f08a017bc" alt="Alarm list in 2.1" height="300"/>

**App version**

2.1 from F-Droid

**Device (please complete the following information):**

 - Model: Google Pixel 5a
 - OS: Android 13

**Additional context**

With just the 2 example alarms I set up for the screenshots it's not that bad, but my real alarms have a lot more because I use them for things other than just waking up, and I really need to be able to see the days to manage them from week to week. I guess I could manually write the days out again in the label but that's not a great solution.

The way it worked in 1.2 was perfect. I don't know if this was an intentional change or just didn't get much thought put into it, but it's definitely a bug for my use case. I downgraded to 1.2 for now.

(Also not a fan of the big gray cards in 2.1 that take up more space and are brighter in a dark room, I use dark mode because I want to screen to be dark, but if it showed the days I could live with it.)

**Comment by BlackyHawky** [comment]
I can confirm that this was an intentional change but, indeed, after several days of use, I'm in favor of reverting to the old behavior.
This will be ok for the next version.

> Also not a fan of the big gray cards in 2.1...

Please, download version 2.2 [here](https://github.com/BlackyHawky/Clock/releases/tag/2.2); I've added the ability to remove backgrounds in the settings.
