### ISSUE TITLE
FR: better indication that timer is paused

### ISSUE THREAD

**Issue by woj-tek** [BlackyHawky/Clock#43]
**Is your feature request related to a problem? Please describe.**
Currently, when timer is paused, only play/pause button is changed, which is not _that_ visible. It would be nice to make it more noticeable (especially considering it's possible to pause it by taping on the timer itself)

**Describe the solution you'd like**
Previous version (I know, I'm a bit terrible with referring to it 🙈 but it had some nicely thought out solutions), in addition to changing the play/pause button, also made the timer digits blink/flash (1s show/hide frequency more or less).

**Use case**
Currently, one can tap on the timer and without focusing on the button and paying more attention may not notice that timer got paused.

**Comment by BlackyHawky** [comment]
It's strange that this little piece of code was removed because it is indeed much better.

This change will be available in the next release. 😉

**Comment by woj-tek** [comment]
Awesome! Thank you! <3
