### ISSUE TITLE
Digital Clock Material You widget doesn't work

### ISSUE THREAD

**Issue by ghost** [BlackyHawky/Clock#44]
**Describe the bug**
Digital Clock Material You widget doesn't work

**To Reproduce**
Long click on the desktop
Choose Widgets
Choose the Clock app (this app)
Choose Digital Clock Material You widget
Choose 'Add to desktop', or drag and drop it

**Expected behavior**
A digital clock widget should be displayed

**Screenshots**

**App version**

Latest (current)

**Device (please complete the following information):**
 - Model: Infinix NOTE 4 Pro (X571)
 - OS: Android Oreo (8.1.0)

**Additional context**

**Comment by BlackyHawky** [comment]
Unfortunately, it's impossible to reproduce your bug on my 2 devices (plus those of other testers) and on Android Studio emulators.

I suppose it worked before?

Are you using a customized version of Android?

Can you provide Android Studio logs please?

**Comment by BlackyHawky** [comment]
Sorry for the inconvenience, but it confirmed my doubts.

Can you please test the apk attachment?

I have separated the activities about the modification of digital widgets and fixing their display on the launcher.

This solves your problem, and now the digital widgets can be modified independently.

Don't hesitate to let me know if you have any comments.

[Clock_2.4-debug.zip](https://github.com/BlackyHawky/Clock/files/15488942/Clock_2.4-debug.zip)

**Comment by ghost** [comment]
Ok, then gimme a moment please...

**Comment by ghost** [comment]
Ok, thank you very much for the fix.

I have tested the attachment and it worked correctly.

I have a small enhancement if you want to merge it.

When i want to add some clock widgets (classic or Material-You and Analog or Digital),
the app shows me the customize widget settings page.

If you could remove this customization page before adding the widget and add the widget directly, it would be appreciated.

And thanks again for that fix.

**Comment by BlackyHawky** [comment]
> Ok, thank you very much for the fix.

You're welcome. 😉

> If you could remove this customization page before adding the widget and add the widget directly, it would be appreciated.

I'm not sure if this is possible while still retaining the ability to edit **digital** widgets by long-pressing on them (for Android 9+).
Analogs widget are not affected.
