### ISSUE TITLE
Better readability for compact timer list

### ISSUE THREAD

**Issue by mimaiself** [BlackyHawky/Clock#45]
I really like the compact list of timers (in version 2.4) on my smartphone. I also think it is very good that the timers in two columns are still shown as a circle on my tablet. A simple list would be very impractical on a tablet display.

**Is your feature request related to a problem? Please describe.**
But, and I find that very disadvantage, the duration of the timer is displayed in the compact list in very small font size!

**Describe the solution you'd like**
A larger font type for the time would certainly be better readable in the compact list. I also think that the preceding 'Duration:' is unnecessary here. The heading 'Timer' and the timer icon on the left side of each card shows what this is about.

**Use case**

**Describe alternatives you've considered**

**Additional context**

**Comment by BlackyHawky** [comment]
@mimaiself: I'm not against this change.

Do the changes in the screenshots below match your expectations?

| Before | After |
| :------: | :----: |
| <img width=200 src="https://github.com/BlackyHawky/Clock/assets/139015663/943978c4-1e7e-40bf-9886-cffbdfe1a2e8"> | <img width=200 src="https://github.com/BlackyHawky/Clock/assets/139015663/38b24951-023b-46ab-be3b-bcb2c14449a1"> |

**Comment by qw123wh** [comment]
> @mimaiself: I'm not against this change.
> 
> Do the changes in the screenshots below match your expectations?
> 
> Before	After
> <img alt="" width="200" src="https://private-user-images.githubusercontent.com/139015663/335556930-943978c4-1e7e-40bf-9886-cffbdfe1a2e8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNjk0MDgsIm5iZiI6MTcxNzE2OTEwOCwicGF0aCI6Ii8xMzkwMTU2NjMvMzM1NTU2OTMwLTk0Mzk3OGM0LTFlN2UtNDBiZi05ODg2LWNmZmJkZmUxYTJlOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQxNTI1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMGVlNDU4MzdhZWQ2NGE5ZGM5NWU2NTM4ZTMxNjU1MWM3ODRiY2I4MTg0OTBmZTkxNTJhNWU3OWY2ZTIyYTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ppPjpIii6xli92qfoiTvE0pvSbtUW0Cw9K01dsM8O64">	<img alt="" width="200" src="https://private-user-images.githubusercontent.com/139015663/335556979-38b24951-023b-46ab-be3b-bcb2c14449a1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNjk0MDgsIm5iZiI6MTcxNzE2OTEwOCwicGF0aCI6Ii8xMzkwMTU2NjMvMzM1NTU2OTc5LTM4YjI0OTUxLTAyM2ItNDZhYi1iZTNiLWJjYjJjMTQ0NDlhMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQxNTI1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTM3YmI0MmQ5NzdiY2M3Njc5NmUxZTM3MTZmOTBmZmMwZTZhNzczZTgxODM3NDA2NWZmYjZmYTUwOTY5ZThkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cl3-8EuHDiuQyXOqzOG7inCQdSaVNg3yoPRciLZuJuE">

Much better in the second screenshot for me. Bigger fonts are better.

**Comment by mimaiself** [comment]
Oops, you have been closing this issue very quickly. I didn't know that it happened so quickly. Sorry.

It also looks better for me, but in my opinion the font type could be a little bigger. At least the same height as the timer symbol and maximum so large that the numbers are not covered by the blue 'new timer' icon.

**Comment by BlackyHawky** [comment]
I'm not going to increase the font size any further, because I have to think about devices with small screens.
The capture below was taken on a nexus S where the display and font size are set to "Default" in the device settings.
The timer time is correctly highlighted and a larger font size would be unnecessary.

<img width="200" src="https://github.com/BlackyHawky/Clock/assets/139015663/f622bc62-bda5-423a-97f7-d7ea1e400511">

Also, I don't want anyone else to tell me that it was better before with a smaller size.

That's why, the current size is an acceptable compromise.

**Comment by mimaiself** [comment]
You're right. I didn't think of devices with a smaller display. So this is really the best compromise.
