### ISSUE TITLE
Change Notification Time

### ISSUE THREAD

**Issue by smjkh** [BlackyHawky/Clock#49]
**Is your feature request related to a problem? Please describe.**
Problem: Unable to modify AOSP's default notification time before an alarm goes off.

**Describe the solution you'd like**
Being able to have the alarm notification sent a specific time before the alarm (I prefer 15 minutes) in the settings.

**Use case**
Currently using the Oxygen OS stock Clock which allows you to receive a notification 15 minutes before an alarm goes off. Especially useful for those who need/use alarms as reminders to do something.

**Describe alternatives you've considered**
Just changing it from its default to 15 or 30 min as opposed to allowing any customizable time.

**Additional context**
That's it but thanks for reading!

**Comment by victusforce** [comment]
Would love this feature.

**Comment by BlackyHawky** [comment]
I worked on it and it will be available in the next version (v2.6).

**Comment by victusforce** [comment]
Thanks
