### ISSUE TITLE
Timer will continue to run if it is set to less than 5 seconds.

### ISSUE THREAD

**Issue by quadratz** [BlackyHawky/Clock#5]
Steps to reproduce:

1. Set timer to less than 5 seconds and click Start.
2. The timer exceeds the applied limit (resulting in a negative value).
3. The timer always stops and ringing at exactly the 5th second, regardless of the setting.

Expectation:
- The timer should stop and sound at the exact time set.

**Comment by qw123wh** [comment]
I also made some tests, I find the same error as you. I am currently unable to find the solution.

**Comment by GokhanKabar** [comment]
can you assign me ?

**Comment by Aladin056** [comment]
Hi @qw123wh  @CikiMomogi  , i am interested by the issue , i would like to know if you are still active on the project because i can fin a solution . Thank you

**Comment by ahmed12345678910111213141516** [comment]
is that is solved? 
i just tried it , the negative number isn't a bug in my eyes , as the ohter clocks app have it 
and the timer doesn't stop in the fifth second

**Comment by BlackyHawky** [comment]
Impossible to find the cause... 😭

**Comment by ghost** [comment]
I test the app and i have some notes:

The timer will continue counting negative (when foreground or background) if set to 1 or 2 secs.
When reaching -4 or higher, it will ring and sound only if in foreground, otherwise will continue counting negative.

**Comment by BlackyHawky** [comment]
> I test the app and i have some notes:
> 
> The timer will continue counting negative (when foreground or background) if set to 1 or 2 secs. When reaching -4 or higher, it will ring and sound only if in foreground, otherwise will continue counting negative.

I've also noticed this, but I can't find the part of the code that causes this bad behavior.

Note: it seems to be the same on the LineageOS clock application.

**Comment by ghost** [comment]
No, @BlackyHawky 

I have another phone (with LineageOS 18.1 -Android 11- on it), and this problem is not found in the Clock app, except when you set the timer for 1 second (i think because the 1 sec. timer is very low or small to handle correctly)

**Comment by BlackyHawky** [comment]
@MaroEldawwy6 
Check out the video below; this is the application compiled from the official [LineageOS repository](https://github.com/LineageOS/android_packages_apps_DeskClock).

It'll confirm what I've said...

<details>
<summary><b>Watch video</b></summary>
<br>

https://github.com/BlackyHawky/Clock/assets/139015663/f458393e-6947-4c89-8480-1ce3d36bdeec

</details>

**Comment by qw123wh** [comment]
@BlackyHawky I found the solution, 

https://github.com/botxxxx/lib-com.android.deskclock/commit/5f19c681d835959ffea71274408ffcf315f7592e

I tested it on the old AOSP clock, the first on the repository that I haven't updated for 3 years; the changes of TimerItemFragment.java works. Now see if you can adapt this to the new code, since the TimerItemFragment.java file no longer exists

**Comment by BlackyHawky** [comment]
@qw123wh 
You are magic !!!! 🎉🎉
Everything is working properly in my modification thanks to you! Many thanks! 🎉🎉

**Comment by BlackyHawky** [comment]
@qw123wh 
You are magic !!!! 🎉🎉
It's an excellent search that unfortunately only works if the application remains in the foreground.

Did you find the same thing?

**Comment by qw123wh** [comment]
@BlackyHawky Yes same problem, I didn't notice it. Partially resolved.

Create a branch with the modification, then we may find some solution to solve it completely

**Comment by BlackyHawky** [comment]
> Create a branch with the modification, then we may find some solution to solve it completely

Or simply include the modification that works and change the title of this issue.

@Nilsu11 It seems to me that you use or have used Omniclock. Am I right?
If so, can you confirm that everything works on this app?
Do you have the source of the repository?

**Comment by Nilsu11** [comment]
Yes, I used it. In Omniclock the issue also exists.

@BlackyHawky 
LineageOS deskclock has fixed it!! (little delay after time's up the ringtone plays)

**Comment by BlackyHawky** [comment]
> LineageOS deskclock has fixed it!! (little delay after time's up the ringtone plays)

@Nilsu11 
I hadn't seen that you'd updated your comment. 

Where did you find the fix?

I'm using a version compiled from the official [repository](https://github.com/LineageOS/android_packages_apps_DeskClock) for testing and the bug is still there.

**Comment by Nilsu11** [comment]
I'm using an official Lineageos build. On my phone it works.

**Comment by BlackyHawky** [comment]
> I'm using an official Lineageos build. On my phone it works.

Can you tell me what version of the app it is? ( Even if I'm not sure it helps... )

**Comment by Nilsu11** [comment]
> > I'm using an official Lineageos build. On my phone it works.
> 
> Can you tell me what version of the app it is? ( Even if I'm not sure it helps... )

21-20240527-NIGHTLY-oriole
App version it tells me 14.

**Comment by odmfl** [comment]
@Nilsu11 extract the apk from your phone and send it here so we can test it too.

**Comment by Nilsu11** [comment]
[DeskClock.apk.zip](https://github.com/user-attachments/files/15747403/DeskClock.apk.zip)

**Comment by odmfl** [comment]
> [DeskClock.apk.zip](https://github.com/user-attachments/files/15747403/DeskClock.apk.zip)

@Nilsu11 I tested the apk I always have the same problem, if you set 3 seconds it sounds at -2.

**Comment by Nilsu11** [comment]
@odmfl @BlackyHawky  It's now fixed in [OmniClock](https://github.com/Nilsu11/android_packages_apps_OmniClock/commit/7b506faaa495c145fc57dfdafd53be8cf4594417)

**Comment by BlackyHawky** [comment]
@Nilsu11 
Does this work when the app is minimized and with the screen off?

Here, the file you modified in Omniclock was modified in 2016 with commit f4c174d... 😅

**Comment by Nilsu11** [comment]
@BlackyHawky Yes it works. I mean something like this [commit](https://github.com/Nilsu11/OpenClock/commit/5ecfbecefd77b9340d75abc2ab6214b5defa3042). This change should do something similar like the one from before. I used the TimerReceiver just as central point, where the message, that the timer starts is delivered. In OmniClock there sadly isn't a void to do this but just the TimerReceiver. I didn't check it on Android Studio nor compile it. This is just to visualize, what I mean.

**Comment by BlackyHawky** [comment]
Unfortunately it only works if you don't pause the timer.

Steps to reproduce:
- set timer to 3 seconds;
- press pause and wait;
- the timer alarm will trigger while it is paused.

In any case, it seems that you are not far from the solution!

**Comment by Nilsu11** [comment]
@BlackyHawky If you put an if clause into the place, where the state is set to timer expire, to check the state the timer can expire from, this issue should be resolved (Hopefully you know what I mean).

I will demonstrate this in OmniClock, but it will have to wait for another commit I am currently working on (This will take a week or two).

**Comment by BlackyHawky** [comment]
> (Hopefully you know what I mean).

No I don't. 😅

> ...but it will have to wait for another commit I am currently working on (This will take a week or two).

This issue was created over 2 years ago, so we're in no hurry. 😉

**Comment by Nilsu11** [comment]
@BlackyHawky Can you try replacing the if else clause [here](https://github.com/BlackyHawky/Clock/blob/main/app/src/main/java/com/best/deskclock/data/TimerModel.java#L709) with this?

```java
if (nextExpiringTimer == null) {
    // Cancel the existing timer expiration callback.
    final PendingIntent pi = PendingIntent.getService(mContext,
                    0, intent, PendingIntent.FLAG_ONE_SHOT | PendingIntent.FLAG_NO_CREATE | PendingIntent.FLAG_IMMUTABLE);
    if (pi != null) {
        mAlarmManager.cancel(pi);
        pi.cancel();
    }
} else if (nextExpiringTimer.getRemainingTime() < 5) {
    startService(intent);
} else if (nextExpiringTimer.getRemainingTime() < 5000) {
    new Handler().postDelayed(new Runnable() {
        public void run () {
            updateAlarmManager();
        }
    }, nextExpiringTimer.getRemainingTime());
} else {
    // Update the existing timer expiration callback.
    final PendingIntent pi = PendingIntent.getService(mContext,
                    0, intent, PendingIntent.FLAG_ONE_SHOT | PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_IMMUTABLE);
    schedulePendingIntent(mAlarmManager, nextExpiringTimer.getExpirationTime(), pi);
}
```

**Comment by BlackyHawky** [comment]
@Nilsu11 
I've tested it but it doesn't work properly when the application is reduced.

Moreover, a long value is missing to apply the `new Handler` function ; perhaps I should set the value to `nextExpiringTimer.getRemainingTime()` ?

Then, are you sure about `nextExpiringTimer.getRemainingTime() < 5` and `nextExpiringTimer.getRemainingTime() < 5000` ?
Why are these values different?

Finally, should i apply this [commit](https://github.com/Nilsu11/OpenClock/commit/5ecfbecefd77b9340d75abc2ab6214b5defa3042) as well?

**Comment by Nilsu11** [comment]
@BlackyHawky Sorry, yes, I forgot you are right the long value should be `nextExpiringTimer.getRemainingTime()`

As for the different values the 5 is for 5 ms. It actually should be 0 but for good measure I used 5. It shouldn't make a difference. The purpose is to start the timer service directly if the time is below 5ms. Before one would have waited 5 seconds when the time is already up. The 5000 is because of the delay of the AlarmManager necessary which should trigger the method again to check if there still is time's up status or not.

No, it's either one or the other. The solution to the timer problem is looking if there is a timer to expire at the remaining time if it is under 5 seconds (min. delay when using alarmManager to trigger something).

**Comment by BlackyHawky** [comment]
@Nilsu11 
After several tests, it seems to work only when the application is open, but not when it is minimized.
It also creates bugs in notifications.

When I think about it, it's strange to have to indicate a condition when the timer is set below 5 seconds.
I suppose this means that a function already present is causing this bug, but which one??

I really don't understand... And I really don't understand why simply saying when timer = 0 ⟶ alarm should trigger doesn't work.

In any case, you may have found part of the solution.
We still need to investigate.
It's really strange... ☹️

**Comment by Nilsu11** [comment]
> When I think about it, it's strange to have to indicate a condition when the timer is set below 5 seconds. I suppose this means that a function already present is causing this bug, but which one??

Simply said we currently use this method: AlarmManager.setExactAndAllowWhileIdle(int, long triggertime, PendingIntent pi)
The issue: The method needs at least 5 seconds to trigger the PendingIntent. Solution: magically trigger the PendingIntent sooner.

That is my current grasp of the issue and I am out of ideas I can currently try.

@BlackyHawky do you have any idea how the notification updates the timer count. I personally think someone can get the timer to expire through the notification update or the graphical update of the timer ui but I'm not sure.

**Comment by BlackyHawky** [comment]
@Nilsu11 
> The method needs at least 5 seconds to trigger the PendingIntent.

What is the source of this information?

> do you have any idea how the notification updates the timer count.

I think it's in the [TimerNotificationBuilder.java](https://github.com/BlackyHawky/Clock/blob/main/app/src/main/java/com/best/deskclock/data/TimerNotificationBuilder.java) file.

I did a few tests and couldn't get anything to work. ☹️

I noticed that a year ago, this problem was reported on the official LineageOS repository. See [here](https://gitlab.com/LineageOS/issues/android/-/issues/5579). Unfortunately, this does not seem to be a priority.

**Comment by Nilsu11** [comment]
@BlackyHawky My last [commit](https://github.com/Nilsu11/OpenClock/commit/fd02db3d980b8861c41cd49440ce2c88bd070725) should fix the issue.

As for the info it is from a forum thread I read a while back. I confirmed it with both alarms and timers back then.

**Comment by BlackyHawky** [comment]
@Nilsu11 
Unfortunately, this only works if the application remains open.
If the application is reduced, the notification is not updated and the timer alarm is not triggered.
It seems that another file needs to be modified, but what?

**Comment by qw123wh** [comment]
@BlackyHawky I tested the new changes made by @Nilsu11 on my devices Android 14 (custom rom), and Samsung Android 14 (official OneUi) the modifications work perfectly even with locked screen. Try to test again with a test apk on your devices.

**Comment by BlackyHawky** [comment]
@qw123wh, @Nilsu11, @odmfl, @gigisforza70, @quadratz
My previous tests were carried out by loading the application directly from Android Studio.
I really couldn't understand why it wasn't working, as using the `Handler` function seems to be the right thing to do (I've read that in some cases it should be used for alarms, but I can't remember where).

Today, I tested it with a clean release version and EVERYTHING WORKS PERFECTLY !
I'm completely surprised !! 😮 
Why didn't I do this before?!! 😅
(The tests were carried out with a Huawei phone running Android 12 and a Samsung tablet running Android 14.)

I think it's time to conclude this topic by validating Nilsu11's modification and I say **thank you for working on it and finding the solution!!** 🎉

I'll post a commit soon because I want to finish working on the widgets (new ones will be added and the code about widgets will be modified to be more consistent).

---

Below, an apk for those who read this topic and want to test.

[Clock_2.8_beta-release.zip](https://github.com/user-attachments/files/17094755/Clock_2.8_beta-release.zip)
