### ISSUE TITLE
Analog clock appears 1 hour behind

### ISSUE THREAD

**Issue by ojppe** [BlackyHawky/Clock#51]
Analog world clocks show time 1 hour behind digital (real) time

Version 2.4
Android 14

**Comment by BlackyHawky** [comment]
A screenshot would be appreciated as this is not the case on my devices with Android 12 & 14.

**Comment by ojppe** [comment]
[Analog](https://github.com/BlackyHawky/Clock/assets/77202355/9ff89811-3814-47b6-bc61-e32545e2bc5c)
[True time](https://github.com/BlackyHawky/Clock/assets/77202355/ac106e7b-d5a3-4e91-a598-f233c5124c65)

I guess the problem is the hour hand moves in binary. If the time is 18:00 the hand immediately moves from the 5 to the 6 and it looks like it behaves normally for like 15 minutes.

**Comment by BlackyHawky** [comment]
> I guess the problem is the hour hand moves in binary.

That's exactly what it is, and it's not a bug.
I agree that the hour hand should be moved between two hours when the minute hand goes past the 30th minute (as on the watches).

> ... and it looks like it behaves normally for like 15 minutes.

I don't understand what you mean?

**Comment by ojppe** [comment]
> I agree that the hour hand should be moved between two hours when the minute hand goes past the 30th minute (as on the watches).

That is a bug right now though?
The hour hand should always keep moving, not just after 30 minutes.

https://ciechanow.ski/mechanical-watch/

**Comment by BlackyHawky** [comment]
The fact that the hour hand has to move all the time should be seen more as an improvement to the existing code (which I didn't create).

If you had told me that the hour hand is on the number 6 when it's 4, 5 or 7 o'clock, that would indeed have been a bug.

But if it's 6:15, 6:30 or 6:45, it's not necessarily a "mistake" for the hour hand to be on the number 6 to indicate part of the hour.

Do you see what I mean?

In any case, I agree that the behavior of the hour hand needs to be improved.

**Comment by ojppe** [comment]
I see what you mean, but I disagree.

One can miss a train after a quick glance, thinking it's 20:59 when it's actually 21:59.

**Comment by BlackyHawky** [comment]
@ojppe 
Can you please try the apk below?
I think it's much better now.

[Clock_2.4-debug.zip](https://github.com/user-attachments/files/15747481/Clock_2.4-debug.zip)

**Comment by ojppe** [comment]
Perfect! thank you
