### ISSUE TITLE
Move restart button of Timer

### ISSUE THREAD

**Issue by MagdyElfeki** [BlackyHawky/Clock#53]
I can not restart second Timer because the plus button appears over restart button. Can you move restart button at other place
Thanks 
![Screenshot_2024-06-05-01-07-23-638_com best deskclock](https://github.com/BlackyHawky/Clock/assets/25636728/d91b6659-3e9a-4c49-8c5d-3eb7d4f39356)

**Comment by BlackyHawky** [comment]
Thank you for creating this issue, as I had already noticed it.

It's not necessary to move the button. 

Indeed, in the next release, we'll be able to move the timer items above the floating action button.
