### ISSUE TITLE
Alarm doesn't ring when phone is off

### ISSUE THREAD

**Issue by CopKillerAnarchist** [BlackyHawky/Clock#6]
Before you ask yes I gave it the permission.

The phone does start but the actual alarm never rings.

**Comment by qw123wh** [comment]
Which phone do you have?  Which processor and which operating system?
On miui doesn't work, but it's miui's fault.

**Comment by qw123wh** [comment]
Ok, I will see if I can solve it, even if it is very difficult

**Comment by CopKillerAnarchist** [comment]
Good luck and thanks

**Comment by qw123wh** [comment]
completed, with recent changes made
