### ISSUE TITLE
Option to keep screen on when timer is going on...

### ISSUE THREAD

**Issue by chromer030** [BlackyHawky/Clock#65]
**Is your feature request related to a problem? Please describe.**

None

**Describe the solution you'd like**

See title

**Use case**

Mostly usable on excercise sessions...

**Comment by BlackyHawky** [comment]
I totally agree with this improvement.

**Comment by humkod** [comment]
It makes sense to keep the screen on when the timer is for a couple minutes, but if the timer is for more than an hour, it would good to allow the phone to turn the screen off to preserve the battery. In the Interface settings, I disabled the "Keep the screen on", but the timer screen stays on the entire time. Could the app be updated to allow a choice between turning the screen on or off during timers?
