### ISSUE TITLE
Setting to toggle vibration when creating new alarms

### ISSUE THREAD

**Issue by ghost** [BlackyHawky/Clock#68]
It'd be nice if we could set alarms to vibrate by default when creating new ones.

**Comment by BlackyHawky** [comment]
@lyonelzd 
It will be available in the next release 😉

**Comment by ghost** [comment]
> @lyonelzd It will be available in the next release 😉

Beautiful, thank you for your work! Been loving the app :)

**Comment by BlackyHawky** [comment]
Note: the default value of the new setting will be deactivated, as vibrations are not necessarily desired.

See this [comment](https://github.com/qw123wh/new-clock/issues/14#issue-1090340992) from the [old repository](https://github.com/qw123wh/new-clock) as well as this [comment](https://github.com/BlackyHawky/Clock/issues/50#issuecomment-2156742925).
