### ISSUE TITLE
Add a list view for timers

### ISSUE THREAD

**Issue by advait404** [BlackyHawky/Clock#7]
Currently, there is no way to view the progress of multiple timers in one screen, and when having more then 3 timers, swiping between then becomes quite tedious.

An approach similar to the simple clock app would be great. A toggle icon in the corner or a setting option to switch between the 'clock style' and 'list style' view can work. Alternatively, adding all the timers in the notification area can have a similar function.

**Comment by qw123wh** [comment]
completed, new timer display added
