### ISSUE TITLE
widget don't show - app doesn't start

### ISSUE THREAD

**Issue by Joppla** [BlackyHawky/Clock#72]
**Describe the bug**

after reboot the widget is not shown anymore. The app won't start anymore.
I succeed to replace the widget, but app still doesn't start.

**To Reproduce**

click on widget: got message that app doesn't want to open.
same if you click on the app in the app drawer.

**Expected behavior**

start of app

**Screenshots**

**App version**

latest update 2.6

**Device (please complete the following information):**
 - Model: 
 - OS: 
fairphone 4

**Additional context**

**Comment by luxdev01** [comment]
Same here

**App version**

v2.6 (F-droid)

**Device**

- Model: Moto E7
- OS: Android 10

**Comment by BlackyHawky** [comment]
@Joppla 
As indicated in the [changelog](https://github.com/BlackyHawky/Clock/releases/tag/2.6), you'll have to reinstall the app due to a change in the database.

**Comment by Joppla** [comment]
Thanks for the tip. That works.
