### ISSUE TITLE
remember last used Time picker style

### ISSUE THREAD

**Issue by WAZAAAAA0** [BlackyHawky/Clock#77]
**Is your feature request related to a problem? Please describe.**
Currently, if you dislike using the Analog style to create new alarms, you have to waste time switching to the Numeric keypad style every single time, it doesn't get remembered.

**Describe the solution you'd like**
Either make it so the last used style gets remembered, or add a relevant new option to the settings, something like this from [ClockPlus](<https://f-droid.org/packages/com.philliphsu.clock2/>):

![ClockPlus_Time_picker_style](https://github.com/BlackyHawky/Clock/assets/12662809/a3f6f36a-47f2-4d47-ad44-53668742f355)

**Comment by BlackyHawky** [comment]
I totally agree with this enhancement.

**Comment by BlackyHawky** [comment]
@WAZAAAAA0 
As I don't know when I'll publish a new version, I'm providing you with a release version below with the requested enhancement.

[Clock_2.6-release.zip](https://github.com/user-attachments/files/16201622/Clock_2.6-release.zip)
