### ISSUE TITLE
a better Numeric keypad design (from Clock+)

### ISSUE THREAD

**Issue by WAZAAAAA0** [BlackyHawky/Clock#78]
**Is your feature request related to a problem? Please describe.**
Honestly the current Numeric keypad design when creating a new alarm is a bit clunky to use.

**Describe the solution you'd like**
The one from [Clock+](<https://github.com/philliphsu/ClockPlus>) is more convenient overall and should just be copied 1:1 (which imo should be the default), here are some of the subtle reasons that make it superior:
- in DeskClock you're at the mercy of the generic numpad included in your own installed keyboard software, which usually comes with unnecessary keys like `#-+,.`, meanwhile Clock+ has a custom-made one for itself
- you can hold down the Delete button to quickly delete everything you typed
- with the `:00` and `:30` shortcuts you can type stuff like `09:00` and `08:30` in just 2 taps
- if the first digit you type is "3" or something bigger it cleverly greys out 6/7/8/9
- if you type `8 2 2` in Clock+ you get a 08:22 alarm, meanwhile in DeskClock you're stuck typing "8" in the Hour field
- if you type `1 2 3` in Clock+ you get a 01:23 alarm, which is a more sane behavior than the 12:03 you get on DeskClock

![ClockPlus_Numeric_keypad](https://github.com/BlackyHawky/Clock/assets/12662809/34d30206-c739-4348-9d7a-92d185882ca3)

**Comment by BlackyHawky** [comment]
The only point I really agree with is this: _you can hold down the Delete button to quickly delete everything you typed_

Maybe this enhancement can be asked [here](https://github.com/material-components/material-components-android)?

For the rest, personally, I won't make any changes because the user is lazy or can't type 4 digits correctly...
In my opinion, adding additional lines of code or files is not worth it.

**Comment by WAZAAAAA0** [comment]
> the user is lazy or can't type 4 digits correctly

funny you say that, I've always considered the Keypad selector *easier* than the Analog one because it feels "too busy" and requires too much touch precision, meanwhile a Keypad is more straightforward

anyway thanks for pointing me to that git
