### ISSUE TITLE
Import/Export for Settings

### ISSUE THREAD

**Issue by UMA1R-01** [BlackyHawky/Clock#79]
**Is your feature request related to a problem? Please describe.**
When moving to different devices, it's easy to import/export settings and alarms in the app rather than doing everything manually. I'm unable to find any such option in the app.

**Describe the solution you'd like**
A simple export & import option.

**Use case**
Makes exporting data across different devices easier.

**Describe alternatives you've considered**
None as of yet.

**Comment by BlackyHawky** [comment]
Since I started working on this application, I've wanted to implement such an option.
Unfortunately, I'm unable to do so. ☹️

**Comment by BlackyHawky** [comment]
@UMA1R-01 @qw123wh @odmfl @Nilsu11 
I've been working on this and I think it will be available for the next version (except for alarms and ringtones, to avoid bugs if the user changes device).

I still need to do some tests (and that's a long time as there are a lot of settings 😅).

In any case, the first tests are good 👍

I'll keep you informed. 😉

You could test the apk attached.

[Clock_2.9_beta-debug.zip](https://github.com/user-attachments/files/17452298/Clock_2.9_beta-debug.zip)

**Comment by BlackyHawky** [comment]
Only 2 bugs found:
~~- widgets do not update~~ ⟶ fix OK
~~- problem when restoring "System theme with AMOLED and an accent color" values~~ ⟶ fix OK
