### ISSUE TITLE
mutual help to improve the app

### ISSUE THREAD

**Issue by qw123wh** [BlackyHawky/Clock#8]
Hi @Andrewerr
I noticed that you have forked the app and are working on a custom rom, I like both forks and custom roms too. I leave you my email address: qw123whreuvkjs@gmail.com

I would like to give you some suggestions for both the clock app and I would also be interested in testing your rom on "RN7 lavender". If you like contact me.

**Comment by BlackyHawky** [comment]
For information: Due to the migration of the repository, commit _[Set default alarm ringtone from settings](https://github.com/BlackyHawky/Clock/commit/e925b659859dfef7171a281c08a95a9fc2b1f1ca)_ has nothing to do with this subject.

**Comment by qw123wh** [comment]
Yes, there are others that could be closed and completed.

18,14,13,12,10,7,6
