### ISSUE TITLE
Request to add feature to set default alarm ringtone in settings

### ISSUE THREAD

**Issue by vishalscodes** [BlackyHawky/Clock#8]
**Is your feature request related to a problem? Please describe.**
Given in title. It should be similar to how there is such an option for timers.

**Describe the solution you'd like**
An option for the same.

**Use case**
To avoid effort.

<img width=200 src="https://github.com/qw123wh/new-clock/assets/104351431/a3812e37-32e5-4e29-bb5d-6fcaad3a983f">

**Comment by BlackyHawky** [comment]
First of all, thank you for respecting the template to create the issue.

It's an option I'd already thought of, so I'm not the only one who wants it.

I'm just finishing working on the authorization management and I'll see what I can do.

**Comment by BlackyHawky** [comment]
@vishalscodes @qw123wh @odmfl
I've finished resolving this issue. However, I need your opinion as the behavior is slightly modified when the alarm is created. Let me explain:

- Before:
When we changed the ringtone of an existing alarm, the selected ringtone became the default ringtone for new alarms created;

- After modification :
The default ringtone for new alarms created will always be the one defined in the application settings and not the one chosen in existing alarms.

Is this disturbing to you? Personally no; I find it even better to have a clear setting that defines the default ringtone for the alarms created.

**Comment by vishalscodes** [comment]
@BlackyHawky No, this isn't disturbing to me either.

**Comment by qw123wh** [comment]
@BlackyHawky I think the new solution is excellent.

**Comment by odmfl** [comment]
@BlackyHawky It's a good solution for me

**Comment by BlackyHawky** [comment]
Great. I'm finishing up a few details in the code and will publish the change in a new commit tonight or tomorrow.

**Comment by BlackyHawky** [comment]
I'm really sorry but I realized that my modification is not working.
Indeed, as soon as I select the default alarm, the timer ringtone also changes. I absolutely can't change this bad behavior and I'm really lost.
I will do more tests in the coming days.
Sorry to disappoint you. 😢

**Comment by BlackyHawky** [comment]
I'm really sorry but I realized that my modification is not working.
Indeed, as soon as I select the default alarm, the timer ringtone also changes. I absolutely can't change this bad behavior and I'm really lost.
I will do more tests in the coming days.
Sorry to disappoint you. 😢

If you want to take a look, I created the branch [default_ringtone](https://github.com/BlackyHawky/Clock/tree/default_ringtone). The problem is mainly in the RingtonePickerActivity.java file

**Comment by BlackyHawky** [comment]
I finally decided to merge my modifications into the main branch (commit 
ec2a3d7), as everything works correctly with the duplicated RingtonePickerActivity.java file.

A `Todo` is indicated in the new file (named RingtonePickerActivityForSettings.java) in case someone else wants to try merging this new file with the original one (RingtonePickerActivity.java).

In the worst-case scenario, we can always go back.

**Comment by BlackyHawky** [comment]
> @BlackyHawky I fixed this todo in my media alarm picker fork. https://github.com/Nilsu11/new-clock/blob/main/app/src/main/java/com/best/deskclock/ringtone/ui/RingtonePickerActivity.java#L188

@Nilsu11 Thanks you a lot for trying to give me a solution. Unfortunately, it doesn't work in my fork 😢

**Comment by BlackyHawky** [comment]
Thanks to your solution which inspired me, I finally got rid of the RingtonePickerActivityForSettings.java file (commit 
add3812), so thank you. 😉
