### ISSUE TITLE
Problem with Tehran's time difference (UTC +3:30)

### ISSUE THREAD

**Issue by sunshinekhan** [BlackyHawky/Clock#82]
Tehran's time difference of two hours with IST is wrongly factored as one hour on the app, this is probably a roll over from Google's Clock app.

<img width=200 src="https://github.com/user-attachments/assets/bb909fc8-08d2-408e-a19b-e1dd0e19e117"><img width=200 src="https://github.com/user-attachments/assets/70ee4d90-d847-4463-9d51-873c776b2eee">

Requesting you to do the needful.

**Comment by BlackyHawky** [comment]
Can you confirm that only this city is affected?

**Comment by sunshinekhan** [comment]
I have cross checked all other the cities in my screenshot, those are unaffected, seems to be something with +3:30 UTC.

**Comment by BlackyHawky** [comment]
I've never worked on the part of the code that manages time zones, but I'll take a look at it.
In any case, I don't have this problem on my phone, so I hope I can find a solution.

**Comment by BlackyHawky** [comment]
@sunshinekhan 
Can you please specify:
- the model of your device;
- the Android version;
- whether stock or custom ROM;
- the language set on your device;
- the time zone of your device;

It's amazing that on my 2 devices with 2 different versions of Android, this bug is impossible to reproduce.

**Comment by sunshinekhan** [comment]
**Information as requested:**
Model: Redmi Note 8 Pro (M1906G7I)
Android Version: 11RP1A.200720.011
ROM: MIUI Global 12.5.10.0(RGGINXM)
Language: English (India)
Time Zone: GMT+05:30

I presume the issue has been fixed by Google a few days back, I had reached out to support simultaneously when writing here. Have you updated your code recently?

**Comment by BlackyHawky** [comment]
> I presume the issue has been fixed by Google a few days back

@sunshinekhan 
You mean there are no more problems on this app? Or on the one from Google?

> Have you updated your code recently?

I've released [version 2.8](https://github.com/BlackyHawky/Clock/releases/tag/2.8) but I haven't touched the code related to this problem.

**Comment by sunshinekhan** [comment]
The one from Google!

![IMG_20241007_185340](https://github.com/user-attachments/assets/d0038330-80e4-4749-aee4-9a32f2dac88e)
![IMG_20241007_185404](https://github.com/user-attachments/assets/5464f8c4-36ac-4ca6-b21b-c507cb7ce978)

**Comment by BlackyHawky** [comment]
@sunshinekhan
According to your screenshots, the time on this app's widget is identical to the time shown on the Google app.

So it's solved?

**Comment by sunshinekhan** [comment]
The widget and app in the screenshots are both Google, but I cross checked on your app also, it's fixed!

**Comment by BlackyHawky** [comment]
This is very good news, and means that the problem was not caused by the application.
