### ISSUE TITLE
Sort the timer list manually and/or automatically

### ISSUE THREAD

**Issue by DamageIncorporated** [BlackyHawky/Clock#84]
**Is your feature request related to a problem? Please describe.**

I make heavy use of timers for different tasks so I always have a list of 10+ timers.

That can get messy very quick as the list is ordered by time of entry an I cannot move timers in the list.

So, timers for similar contexts may end up on opposite ends of the list and there's nothing I can do about it

**Describe the solution you'd like**

Make entries in the timer list movable by long-tap or a "grip" symbol

**Use case**

Less chaotic list for people with many timers

**Describe alternatives you've considered**

A complete "sort by" feature offering different criteria to sort the list like date added, A-Z, used often, last used etc.

**Additional context**

**Comment by BlackyHawky** [comment]
I'd also like to have this improvement; enabling timer dragging is simple, but it's impossible to save the list after dragging.
I have no idea how to do it.

**Comment by DamageIncorporated** [comment]
Maybe sorting could be workaround?

even if it is impossible to save the list order permanently, is it possible to re-run a sort function each time the list is displayed?

While that may seem aggressive, a switch to disable automatic sorting in settings could restore todays behaviour if one wants or needs it this way. 

the sort order would also need to be set in the preferred way: I need sorting by name A-Z, but sorting by date new-old or other criteria may also be useful to some 😀

**Comment by BlackyHawky** [comment]
@DamageIncorporated 
I've tried working on this again and I'm absolutely unable to save the timer list after dragging one of these items.
So I'm going to stop working on it.

However, in the commit 8948869, I've added a setting that sorts timers by creation date, by duration in ascending or descending order and by name. I hope it's already a small improvement.

I'll provide you with a beta version of the application if you'd like to give it a try.

[Clock_2.9_beta-release.zip](https://github.com/user-attachments/files/17283016/Clock_2.9_beta-release.zip)

**Comment by BlackyHawky** [comment]
@DamageIncorporated, @qw123wh, @odmfl, @Nilsu11 

I've been working on this and the only thing I've managed to do is to sort the timers by creation date (new ones at the top), by ascending or descending duration and by name.

This sorting is defined in the timer parameters and is only applied when timers are reset or have expired.
This means that newly added timers therefore appear at the top of the list, before being automatically sorted when they are reset or have expired.

Finally, I couldn't get the existing timers to appear at the top of the list when played (I could only do this if there was only one timer).

So, do you think I should validate my modification?

**Comment by odmfl** [comment]
The new timers are already on top, it might change to top just from alphabetical order. I don't know when it's actually useful

**Comment by BlackyHawky** [comment]
@odmfl 
> The new timers are already on top, it might change to top just from alphabetical order. I don't know when it's actually useful

All new timers will be at the top regardless of the sorting set in the settings. Timers will only be sorted if they are reset.

**Comment by Nilsu11** [comment]
@BlackyHawky 
getTimers() in TimerAdapter should look like this: `private List<Timer> getTimers() {
        List<Timer> timers = DataModel.getDataModel().getTimers();
        if (timers.size() > 1) {
            switch (DataModel.getDataModel().getTimerSortingPreference()) {
                case KEY_SORT_TIMERS_BY_CREATION_DATE ->
                        Collections.sort(timers, Timer.ID_COMPARATOR);
                case KEY_SORT_TIMERS_BY_ASCENDING_DURATION ->
                        Collections.sort(timers, Timer.ASCENDING_DURATION_COMPARATOR);
                case KEY_SORT_TIMERS_BY_DESCENDING_DURATION ->
                        Collections.sort(timers, Timer.DESCENDING_DURATION_COMPARATOR);
                case KEY_SORT_TIMERS_BY_NAME -> Collections.sort(timers, Timer.NAME_COMPARATOR);
            }
        }
        return timers;
    }` if every timer should be sorted since creation

Tested only with duration settings.
you also need to update the adapter list on preference change somehow (currently app needs to be restarted)

**Comment by BlackyHawky** [comment]
@Nilsu
Since my last post I've found a better solution.

By the way, in my solution, existing timers that are running are at the top of the list, sorted by ascending duration.
Once they are reset or expired, they are sorted again in the order defined in the timer setting.

I don't understand why I didn't find it before because it was so obvious! 😅

If I have time today, I'll post a new commit. 😉

**Comment by BlackyHawky** [comment]
With the commits 43928fe and ecac9d3, timer sorting is fully functional and similar to the Google application.
The advantage over the Google application is that timers can be sorted by creation date, duration (ascending or descending) and name.
All that remains is to find a solution for sorting timers manually.

**Comment by BlackyHawky** [comment]
With the commits 43928fe and 678e832, timer sorting is fully functional and similar to the Google application.
The advantage over the Google application is that timers can be sorted by creation date, duration (ascending or descending) and name.
All that remains is to find a solution for sorting timers manually.

(Sorry for the useless commits polluting this thread, I was wrong about Android Studio.)

**Comment by qw123wh** [comment]
> @DamageIncorporated, @qw123wh, @odmfl, @Nilsu11
> 
> I've been working on this and the only thing I've managed to do is to sort the timers by creation date (new ones at the top), by ascending or descending duration and by name.
> 
> This sorting is defined in the timer parameters and is only applied when timers are reset or have expired. This means that newly added timers therefore appear at the top of the list, before being automatically sorted when they are reset or have expired.
> 
> Finally, I couldn't get the existing timers to appear at the top of the list when played (I could only do this if there was only one timer).
> 
> So, do you think I should validate my modification?

yes I find these changes very interesting

**Comment by BlackyHawky** [comment]
I've finally managed to solve this enhancement completely.

In the end, timers can be sorted manually, in ascending order of duration, descending order of duration or by name. 👌
