### ISSUE TITLE
Change background when alarm is triggered

### ISSUE THREAD

**Issue by BlackyHawky** [BlackyHawky/Clock#85]
### Discussed in https://github.com/BlackyHawky/Clock/discussions/80

<div type='discussions-op-text'>

<sup>Originally posted by **timofort** July 21, 2024</sup>
Hello and thank you for proposing new version of Clock.

In 1.2 version, alarm started with our own phone lockscreen as background. Not anymore, in 2.5 version for exemple.

Is it possible to put back this feature in next release(s), and extend it to timer in addition ?

Thanks.

Timofort</div>

**Comment by BlackyHawky** [comment]
@timofort
Your request will be available in the next release.
Regarding the timer alarm background, I will make another commit.

**Comment by timofort** [comment]
Thank you. Very kind ;)

**Comment by BlackyHawky** [comment]
@timofort 
FYI: it will be possible to have a transparent background for expired timers thanks to commit a7bde93.
