### ISSUE TITLE
Light mode on lock screen alarm

### ISSUE THREAD

**Issue by idonotbelonghere** [BlackyHawky/Clock#86]
My phone has a black and white E-ink screen and the black on white interface is the reason I'm using your clock app.
I'd love to have a light mode option for the lock screen alarm notification too.

**Comment by BlackyHawky** [comment]
Your request is taken into account with the commit 2ce7225.
In the next release, all colors in this view will be editable.

**Comment by idonotbelonghere** [comment]
🥰
