### ISSUE TITLE
Alarm programming

### ISSUE THREAD

**Issue by Nalajalan** [BlackyHawky/Clock#89]
Hi,

It seems to me than a FOSS app forked from ASOP Clock app that implement complete functionalities of Google Clock and more is just indispensable.

So thank a lot for your app.

Speaking of that, if I'm not mistaken, programming option of Google Clock is missing. It's a must have function for me, so I'll be more than happy to replace my not FOSS Google Clock by this one if it's implemented.

<img width=200 src="https://github.com/user-attachments/assets/69f52217-1cac-4337-96c5-473a68424963"><img width=200 src="https://github.com/user-attachments/assets/88bb21aa-1cce-4824-917d-d4146fd73d56">

**Comment by BlackyHawky** [comment]
Thank you for your compliment. I do the best I can even if unfortunately I don't have enough knowledge to do some things. 😬

I'm closing this topic because it's a duplication with #4 where unfortunately I need help to implement this addition.
