### ISSUE TITLE
Smaller font in alarm list

### ISSUE THREAD

**Issue by arnoulfos** [BlackyHawky/Clock#91]
Hi , I would like a smaller font in the alarm list page to see all alarms without scrolling when I have a lot thanks in advance

**Comment by BlackyHawky** [comment]
What text(s) are you talking about?

I won't change the height of the elements that can be touched because they respect Android's recommendations, i.e. 48dp (see [here](https://support.google.com/accessibility/android/answer/7101858?hl=en))

**Comment by arnoulfos** [comment]
All right but at least the elements could be organized in a more compact way that fit more alarms in the list visible in the screen. Thanks in advance

**Comment by BlackyHawky** [comment]
I'm sorry, but I don't see how I can rearrange the alarms.
There's already a reduced view showing the main information and an extended view to show more options.

If I reduce anything, someone else will most likely open a problem saying it's too small.
I hope you understand that I can't please everyone with all the different screen sizes.

**Comment by arnoulfos** [comment]
I have a very big screen but on my screen in the list fit 4 alarms only with the app while 6 in the stock app (screenshot)

<img width=200 src="https://github.com/user-attachments/assets/d4857d03-dda8-4397-9521-e7b87c512495">

<img width=200 src="https://github.com/user-attachments/assets/1f8c19d7-5b40-4067-832a-8884f82105b6">

**Comment by BlackyHawky** [comment]
I'll give it a try in a few days, then offer you the opportunity to test a beta version and let me know what you think.

**Comment by arnoulfos** [comment]
Thanks a lot!

Aug 26, 2024 12:35:09 BlackyHawky ***@***.***>:

**Comment by BlackyHawky** [comment]
@arnoulfos 
Can you test the attached apk and give me your opinion please?

You should now have 5 alarms displayed.

To get 6, I'd have to play with the height of the title, but I won't do that because I don't want to change the minimum height of the elements that can be touched as indicated in my previous comment.

In any case, you should find the display much better now.

[Clock_2.6-debug.zip](https://github.com/user-attachments/files/16789798/Clock_2.6-debug.zip)

**Comment by arnoulfos** [comment]
Yes it is a bit better , thanks a lot. And could not be reduced a little bit the white space between the alarms?

Aug 29, 2024 01:56:43 BlackyHawky ***@***.***>:

**Comment by BlackyHawky** [comment]
Currently, the alarm list is separated by a space equal to 10dp (as are the city and timer lists).

Maybe I can reduce this value to 8dp but I won't never go below 8dp.
I'll have to test again and keep you informed.

**Comment by arnoulfos** [comment]
All right, thanks a lot!

Aug 29, 2024 11:06:02 BlackyHawky ***@***.***>:

**Comment by BlackyHawky** [comment]
@arnoulfos 
You can test the attached file again; all the margins of each view have been reduced to 8dp.
I won't go below this value.

[Clock_2.6-debug.zip](https://github.com/user-attachments/files/16918506/Clock_2.6-debug.zip)

**Comment by arnoulfos** [comment]
Yes thanks a lot , just the top line that writes  alarm at the top is unuseful, the "alarm" text and icon  could be in bold or another color to show that we are on this tab and the "setting " icon could be put at the bottom instead of the "bedtime" text and icon , as you know the proverb  : "less is more"! Thanks a lot

Sep 7, 2024 16:56:35 BlackyHawky ***@***.***>:

**Comment by BlackyHawky** [comment]
> Yes thanks a lot , just the top line that writes  alarm at the top is unuseful, the "alarm" text and icon  could be in bold or another color to show that we are on this tab and the "setting " icon could be put at the bottom instead of the "bedtime" text and icon , as you know the proverb  : "less is more"! Thanks a lot

Your comment is not related to your original request. We mustn't mix topics.

In any case, I won't be changing the current main interface.
