### ISSUE TITLE
Add support for repetitive/recurring alarm

### ISSUE THREAD

**Issue by tenzap** [BlackyHawky/Clock#93]
**Is your feature request related to a problem? Please describe.**

I would like to be able to have repetitive/recurring alarm. For example, from 8.00 to 20.00 I would like to have an alarm ring every 30minutes.
This would be the configuration of one alarm. Objective is to avoid having to set an alarm for each occurrence individually.

**Describe the solution you'd like**

See above

**Use case**

See above 

**Describe alternatives you've considered**

This app supports it, but it's not open source AFAICT.
https://play.google.com/store/apps/details?id=com.kittoboy.repeatalarm&hl=en_US

Its description says:
Only four fields are required to set alarms!😁
✓ Alarm Name
✓ Repeat Day
✓ Start and End Time
✓ Alarming Intervals

**Additional context**

**Comment by DJCrashdummy** [comment]
@tenzap try [Hourly Reminder](https://f-droid.org/packages/com.github.axet.hourlyreminder/)... it is FOSS and should be able to do what you want.

**Comment by tenzap** [comment]
Thanks @DJCrashdummy ! Looks promising.
