### ISSUE TITLE
Add rotating date to analog material you widget

### ISSUE THREAD

**Issue by neunzehnachtneun** [BlackyHawky/Clock#97]
Please add the option to show the date like google clock does. If needed, I can add screenshots.

Thanks!

**Comment by BlackyHawky** [comment]
I assume you mean the vertical widget?

Edit: I'm working on it and it will be available in the next version.

**Comment by neunzehnachtneun** [comment]
Thanks for adding the vertical widgt.

In fact I was looking for something different: I really like the analog scallop widget. The google app shows the weekday and the date rotating opposite the second hand.

**Comment by BlackyHawky** [comment]
Ahhh! So it's not the vertical widget you wanted. 😅

Can you please open a new issue with the title: “Showing date as opposed to seconds for analog widgets”?
I gave it a try (very quickly) a long time ago and didn't succeed. I'll try again soon.
