### ISSUE TITLE
Some settings seems to be lost after upgrade to 2.7

### ISSUE THREAD

**Issue by woj-tek** [BlackyHawky/Clock#99]
**Describe the bug**
Yesterday I updated to 2.7 and noticed that some settings got lost (dark theme went from amoled to dark, gradual alarm also was disabled).

**Expected behavior**
Settings should stick :)

**App version**
2.7 f-droid

**Device (please complete the following information):**
 - Model: Galaxy a52s
 - OS: Android 14

**Additional context**

One thing I noticed is that alarm screen (with swipe to postpone and cancel alarm is "dark" instead of "amoled black" even though I set the theme in the app)

**Comment by BlackyHawky** [comment]
I'm sorry for the inconvenience and thank you for reporting it.

This is due to commit e803241 where I changed some key names to make them more consistent.

Unfortunately, it will be the same for the next version, but this time I'll identify the settings concerned.

The app is constantly evolving and I'm doing my best to ensure that it can be properly and easily maintained by someone else in the future, if I ever stop developing it.

In any case, let's be reassured: when we redefine the settings everything is saved correctly and everything is functional. 😉

**Comment by woj-tek** [comment]
> This is due to commit [e803241](https://github.com/BlackyHawky/Clock/commit/e8032414a73865af081002a56c1f3abc8eb05668) where I changed some key names to make them more consistent.
> 
> Unfortunately, it will be the same for the next version, but this time I'll identify the settings concerned.


Consistency is good (and always "optimise for readability" <3) :) though... from what I remember android does support database migration so maybe it could be possible to utlise the mechanism to avoid preference loss?


Btw. the issue with alarm screen not having correct background - should I report it separately? :)

**Comment by BlackyHawky** [comment]
> Consistency is good (and always "optimise for readability" <3) :) though... from what I remember android does support database migration so maybe it could be possible to utlise the mechanism to avoid preference loss?

Perhaps it's possible, but I'm not familiar with this type of function.
As far as I know, if I change the name of a preference key, the value associated with that key is reset to its default value.

> Btw. the issue with alarm screen not having correct background - should I report it separately? :)

Now that the alarm view is customizable, you can change the background color yourself using the "Background color" setting, specifying `ff000000` as the color in the hex field.

Maybe I can automate that. I'll give it a try soon and keep you informed.

**Comment by woj-tek** [comment]
> Now that the alarm view is customizable, you can change the background color yourself using the "Background color" setting, specifying `ff000000` as the color in the hex field.

Missed the option, now it looks good, thank you! <3

**Comment by BlackyHawky** [comment]
@woj-tek 
Thanks to the commit b9d960b, the default background color of the alarm correctly and automatically follows the amoled mode.

**Comment by woj-tek** [comment]
@BlackyHawky thank you so much 🤎
